//go:build !wago_precompiled && wago_profile

package wago

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sync"
	"testing"

	"github.com/wago-org/wago/internal/jitprofile"
)

func TestCodeProfileSharedLifecycleAndCodeNeutrality(t *testing.T) {
	s := NewCodeProfile(CodeProfileOptions{IncludeCode: true, SourceMaps: true, UnwindMaps: true})
	defer s.Close()
	plain, err := Compile(identityI32Module())
	if err != nil {
		t.Fatal(err)
	}
	defer plain.Close()
	c, err := Compile(NewRuntimeConfig().WithCodeProfile(s), identityI32Module())
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	if !bytes.Equal(plain.code, c.code) {
		t.Fatal("profiling changed generated bytes")
	}
	a, err := Instantiate(c)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	b, err := Instantiate(c)
	if err != nil {
		t.Fatal(err)
	}
	defer b.Close()
	events, status := s.Read(0)
	if status.Dropped != 0 || len(events) != 1 {
		t.Fatal(events, status)
	}
	im := events[0].Image
	if err := jitprofile.ValidateRegions(im.Regions, im.Size); err != nil {
		t.Fatal(err)
	}
	if runtime.GOARCH == "amd64" {
		if len(im.Unwind) == 0 || im.UnwindCoverage != "amd64-fixed-frames-and-adapters" {
			t.Fatalf("missing compiler unwind rules: %+v", im)
		}
	} else if len(im.Unwind) != 0 || im.UnwindCoverage != "unsupported" {
		t.Fatalf("unqualified target claims unwind support: %+v", im)
	}
	if len(im.Functions) != 1 || im.Functions[0].Index != 0 {
		t.Fatal(im.Functions)
	}
	c.Close()
	a.Close()
	events, _ = s.Read(0)
	if len(events) != 1 {
		t.Fatal("early retirement", events)
	}
	got, err := b.Invoke("identity", 41)
	if err != nil || got[0] != 41 {
		t.Fatal(got, err)
	}
	b.Close()
	events, _ = s.Read(0)
	if len(events) != 2 || events[1].Kind != "retire" {
		t.Fatal(events)
	}
	if !bytes.Equal(events[0].Image.Code, plain.code) {
		t.Fatal("bytes not retained after teardown")
	}
}
func TestCodeProfileStartAndImportIndex(t *testing.T) {
	s := NewCodeProfile(CodeProfileOptions{IncludeCode: true})
	defer s.Close()
	c, err := Compile(NewRuntimeConfig().WithCodeProfile(s), hostImportStartModule())
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	called := false
	imports := NewImports()
	imports.HostFunc("env", "f", func(HostCall) {
		called = true
		images, _, status := s.Snapshot()
		if status.Dropped != 0 || len(images) != 2 {
			t.Errorf("start executed before registrations: %d %+v", len(images), status)
		}
	})
	in, err := Instantiate(c, InstantiateOptions{Imports: imports})
	if err != nil {
		t.Fatal(err)
	}
	defer in.Close()
	if !called {
		t.Fatal("start not called")
	}
	events, _ := s.Read(0)
	if events[0].Image.Functions[0].Index != 1 {
		t.Fatal("local index mistaken for full index")
	}
	c.Close()
	in.Close()
	images, _, _ := s.Snapshot()
	if len(images) != 0 {
		t.Fatal("mapping retained", images)
	}
}
func TestCodeProfileConcurrentInstances(t *testing.T) {
	s := NewCodeProfile(CodeProfileOptions{})
	defer s.Close()
	c, err := Compile(NewRuntimeConfig().WithCodeProfile(s), identityI32Module())
	if err != nil {
		t.Fatal(err)
	}
	var wg sync.WaitGroup
	for i := 0; i < 12; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for n := 0; n < 10; n++ {
				in, err := Instantiate(c)
				if err != nil {
					t.Error(err)
					return
				}
				in.Close()
			}
		}()
	}
	wg.Wait()
	c.Close()
	events, status := s.Read(0)
	if len(events) != 2 || status.Dropped != 0 {
		t.Fatal(len(events), status)
	}
}

func TestCodeProfileArtifactReloadIsExplicitlyUnknown(t *testing.T) {
	c, err := Compile(identityI32Module())
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	blob, err := c.MarshalBinary()
	if err != nil {
		t.Fatal(err)
	}
	loaded, err := LoadTrustedArtifact(blob)
	if err != nil {
		t.Fatal(err)
	}
	defer loaded.Close()
	s := NewCodeProfile(CodeProfileOptions{IncludeCode: true})
	defer s.Close()
	if err := loaded.AttachCodeProfile(s); err != nil {
		t.Fatal(err)
	}
	in, err := Instantiate(loaded)
	if err != nil {
		t.Fatal(err)
	}
	defer in.Close()
	images, _, status := s.Snapshot()
	if status.Dropped != 0 || len(images) != 1 {
		t.Fatal(images, status)
	}
	if images[0].ModuleID != "" || len(images[0].Regions) != 1 || images[0].Regions[0].Kind != "unknown" || len(images[0].CodeSites) != 0 || images[0].SiteCoverage != "" {
		t.Fatal("invented artifact metadata", images[0])
	}
	if len(images[0].Code) == 0 {
		t.Fatal("missing requested bytes")
	}
}

func BenchmarkCodeProfileInvocation(b *testing.B) {
	for _, enabled := range []bool{false, true} {
		name := "disabled"
		if enabled {
			name = "enabled"
		}
		b.Run(name, func(b *testing.B) {
			session := NewCodeProfile(CodeProfileOptions{})
			defer session.Close()
			cfg := NewRuntimeConfig()
			if enabled {
				cfg = cfg.WithCodeProfile(session)
			}
			c, err := Compile(cfg, identityI32Module())
			if err != nil {
				b.Fatal(err)
			}
			defer c.Close()
			in, err := Instantiate(c)
			if err != nil {
				b.Fatal(err)
			}
			defer in.Close()
			fn, err := in.WasmFunc("identity")
			if err != nil {
				b.Fatal(err)
			}
			b.ReportAllocs()
			b.ResetTimer()
			for i := 0; i < b.N; i++ {
				out, err := fn.Invoke(37)
				if err != nil || out[0] != 37 {
					b.Fatal(out, err)
				}
			}
		})
	}
}

func TestCodeProfileCorpusLayouts(t *testing.T) {
	b, err := os.ReadFile("../../corpus/catalog.json")
	if err != nil {
		t.Fatal(err)
	}
	var catalog struct {
		Benchmarks []struct {
			ID       string `json:"id"`
			Artifact string `json:"artifact"`
		} `json:"benchmarks"`
	}
	if err = json.Unmarshal(b, &catalog); err != nil {
		t.Fatal(err)
	}
	selected := map[string]bool{"json-as": true, "json-as-simd": true, "many_funcs": true, "matmul": true}
	for _, entry := range catalog.Benchmarks {
		if selected[entry.ID] {
			t.Run(entry.ID, func(t *testing.T) {
				source, err := os.ReadFile(filepath.Join("../../corpus", entry.Artifact))
				if err != nil {
					t.Fatal(err)
				}
				for _, workers := range []int{1, 4} {
					cfg := NewRuntimeConfig().WithFunctionWorkers(workers)
					plain, err := Compile(cfg, source)
					if err != nil {
						t.Fatal(err)
					}
					session := NewCodeProfile(CodeProfileOptions{SourceMaps: true})
					observed, err := Compile(cfg.WithCodeProfile(session), source)
					if err != nil {
						plain.Close()
						t.Fatal(err)
					}
					if !bytes.Equal(plain.code, observed.code) {
						t.Fatal("profiling changed corpus code", workers)
					}
					plain.Close()
					observed.Close()
					session.Close()
				}
			})
		}
	}
}

func TestCodeProfileAttachLiveMappings(t *testing.T) {
	for _, closeCompiled := range []bool{false, true} {
		t.Run(fmt.Sprint("closed=", closeCompiled), func(t *testing.T) {
			c, err := Compile(benchReturningImportModule())
			if err != nil {
				t.Fatal(err)
			}
			defer c.Close()
			imports := testImports("env.f", slotHostFunc(func(_ HostModule, args, results []uint64) { results[0] = args[0] + 1 }))
			in, err := Instantiate(c, imports)
			if err != nil {
				t.Fatal(err)
			}
			defer in.Close()
			if closeCompiled {
				if err := c.Close(); err != nil {
					t.Fatal(err)
				}
			}
			s := NewCodeProfile(CodeProfileOptions{IncludeCode: true, SourceMaps: true})
			defer s.Close()
			if err := c.AttachCodeProfile(s); err != nil {
				t.Fatal(err)
			}
			if err := c.AttachCodeProfile(s); err != nil {
				t.Fatal("idempotent live attach", err)
			}
			images, cursor, status := s.Snapshot()
			if status.Dropped != 0 || len(images) != 2 {
				t.Fatal(len(images), status)
			}
			kinds := map[string]bool{}
			for _, im := range images {
				if !im.Preexisting || len(im.Code) == 0 || im.SourceCoverage != "" || len(im.Functions) != 0 || len(im.CodeSites) != 0 || im.SiteCoverage != "" {
					t.Fatal("invented or missing metadata", im)
				}
				kinds[im.Regions[0].Kind] = true
			}
			if !kinds["unknown"] || !kinds["host-thunk"] {
				t.Fatal(kinds)
			}
			if got, err := in.Invoke("g", 41); err != nil || len(got) != 1 || got[0] != 42 {
				t.Fatal(got, err)
			}
			if err := c.Close(); err != nil {
				t.Fatal(err)
			}
			if err := in.Close(); err != nil {
				t.Fatal(err)
			}
			events, status := s.Read(cursor)
			if status.Dropped != 0 || len(events) != 2 {
				t.Fatal(events, status)
			}
			for _, event := range events {
				if event.Kind != "retire" {
					t.Fatal(event)
				}
			}
			if active, _, _ := s.Snapshot(); len(active) != 0 {
				t.Fatal("retained images", active)
			}
			// The copied bytes remain valid after both real mappings are unmapped.
			all, _ := s.Read(0)
			for i, im := range images {
				if !bytes.Equal(im.Code, all[i].Image.Code) {
					t.Fatal("lost retained code")
				}
			}
		})
	}
}

func TestCodeProfileAttachRejectsLiveBoundaryTracing(t *testing.T) {
	c, err := Compile(identityI32Module())
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	in, err := Instantiate(c)
	if err != nil {
		t.Fatal(err)
	}
	defer in.Close()
	s := NewCodeProfile(CodeProfileOptions{TraceBoundaries: true})
	defer s.Close()
	if err := c.AttachCodeProfile(s); err == nil {
		t.Fatal("attached tracing midway through execution")
	}
	if c.codeCache.loadProfile() != nil {
		t.Fatal("failed attach changed module")
	}
}

func TestCodeProfileAttachOwnedThunksAndConcurrentRetirement(t *testing.T) {
	rt := NewRuntime()
	defer rt.Close()
	mod, err := rt.Compile(benchReturningImportModule())
	if err != nil {
		t.Fatal(err)
	}
	defer mod.Close()
	owner, err := rt.NewHostFuncRef(slotHostFunc(func(_ HostModule, args, results []uint64) { results[0] = args[0] + 1 }), FuncSig{Params: []ValType{ValI32}, Results: []ValType{ValI32}})
	if err != nil {
		t.Fatal(err)
	}
	defer owner.Close()
	instantiate := func() (*Instance, error) {
		return rt.Instantiate(context.Background(), mod, WithImports(testImports("env.f", owner)))
	}
	held, err := instantiate()
	if err != nil {
		t.Fatal(err)
	}
	defer held.Close()
	if len(held.thunkMem) == 0 {
		t.Fatal("missing private thunk")
	}
	s := NewCodeProfile(CodeProfileOptions{IncludeCode: true})
	defer s.Close()
	start := make(chan struct{})
	errs := make(chan error, 8)
	var wg sync.WaitGroup
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			for j := 0; j < 20; j++ {
				in, err := instantiate()
				if err != nil {
					errs <- err
					return
				}
				if _, err = in.Invoke("g", 41); err != nil {
					_ = in.Close()
					errs <- err
					return
				}
				if err = in.Close(); err != nil {
					errs <- err
					return
				}
			}
		}()
	}
	close(start)
	if err := mod.Compiled().AttachCodeProfile(s); err != nil {
		t.Fatal(err)
	}
	// Snapshot-plus-cursor and later events must not leave stale active mappings.
	initial, cursor, status := s.Snapshot()
	if status.Dropped != 0 || len(initial) < 2 {
		t.Fatal(len(initial), status)
	}
	active := map[uint64]bool{}
	for _, im := range initial {
		active[im.ID] = true
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Error(err)
	}
	if err := held.Close(); err != nil {
		t.Fatal(err)
	}
	if err := mod.Close(); err != nil {
		t.Fatal(err)
	}
	if err := rt.Close(); err != nil {
		t.Fatal(err)
	}
	events, status := s.Read(cursor)
	if status.Dropped != 0 {
		t.Fatal(status)
	}
	for _, event := range events {
		switch event.Kind {
		case "load":
			if active[event.ImageID] {
				t.Fatal("duplicate generation", event.ImageID)
			}
			active[event.ImageID] = true
		case "retire":
			if !active[event.ImageID] {
				t.Fatal("retirement without observation", event.ImageID)
			}
			delete(active, event.ImageID)
		}
	}
	if len(active) != 0 {
		t.Fatal("unretired mappings", active)
	}
	images, _, _ := s.Snapshot()
	if len(images) != 0 {
		t.Fatal("active images after teardown", images)
	}
	all, _ := s.Read(0)
	foundPrivate := false
	for _, event := range all {
		if event.Kind == "load" {
			im := event.Image
			if len(im.Code) != int(im.Size) {
				t.Fatal("missing stable bytes", im.ID)
			}
			if im.Preexisting && len(im.Regions) == 1 && im.Regions[0].Kind == "host-thunk" {
				foundPrivate = true
			}
		}
	}
	if !foundPrivate {
		t.Fatal("lost preexisting private thunk")
	}
	cc := held.c.loadCodeCache()
	cc.profileMu.Lock()
	retained := len(cc.liveProfileThunks)
	cc.profileMu.Unlock()
	if retained != 0 {
		t.Fatal("retained retired thunk views", retained)
	}
}
