// Command railspecgen validates the RailSpec JSON contract and emits its dense
// Go rule table.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
)

type contract struct {
	Schema  string `json:"$schema"`
	Version uint32 `json:"version"`
	Rules   []rule `json:"rules"`
}

type rule struct {
	ID          string   `json:"id"`
	GoName      string   `json:"go_name"`
	Targets     []string `json:"targets"`
	Forms       []string `json:"forms"`
	NativeBytes uint8    `json:"native_bytes"`
	Latency     uint8    `json:"latency"`
	Uops        uint8    `json:"uops"`
	Verified    bool     `json:"verified"`
}

var goNamePattern = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)

var targetNames = map[string]string{
	"amd64": "TargetAMD64",
	"arm64": "TargetARM64",
}

var formNames = map[string]string{
	"register":       "FormRegister",
	"signed-imm32":   "FormSignedImm32",
	"fixed-gpr-1":    "FormFixedGPR1",
	"fixed-gpr-0":    "FormFixedGPR0",
	"unsigned-imm12": "FormUnsignedImm12",
	"address":        "FormAddress",
	"flags":          "FormFlags",
}

func main() {
	specPath := flag.String("spec", "core_rules.json", "RailSpec JSON contract")
	outPath := flag.String("out", "rules_gen.go", "generated Go output")
	check := flag.Bool("check", true, "fail if generated output is stale")
	flag.Parse()
	data, err := os.ReadFile(*specPath)
	failIf(err)
	var spec contract
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	failIf(decoder.Decode(&spec))
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			err = fmt.Errorf("railspec: trailing JSON value")
		}
		failIf(err)
	}
	failIf(validate(spec))
	generated, err := generate(spec)
	failIf(err)
	if *check {
		current, readErr := os.ReadFile(*outPath)
		failIf(readErr)
		if !bytes.Equal(current, generated) {
			failIf(fmt.Errorf("%s is stale; run go generate", *outPath))
		}
		return
	}
	temporary := *outPath + ".tmp"
	failIf(os.WriteFile(temporary, generated, 0o644))
	failIf(os.Rename(temporary, *outPath))
}

func validate(spec contract) error {
	if spec.Version != 1 {
		return fmt.Errorf("railspec: unsupported version %d", spec.Version)
	}
	if len(spec.Rules) == 0 || len(spec.Rules) > 255 {
		return fmt.Errorf("railspec: rule count %d is outside [1,255]", len(spec.Rules))
	}
	ids, names := map[string]bool{}, map[string]bool{}
	for index, rule := range spec.Rules {
		if rule.ID == "" || ids[rule.ID] {
			return fmt.Errorf("railspec: rule %d has empty or duplicate id %q", index, rule.ID)
		}
		if !goNamePattern.MatchString(rule.GoName) || names[rule.GoName] {
			return fmt.Errorf("railspec: rule %q has invalid or duplicate go_name %q", rule.ID, rule.GoName)
		}
		ids[rule.ID], names[rule.GoName] = true, true
		if len(rule.Targets) == 0 || len(rule.Forms) == 0 || len(rule.Forms) > 3 {
			return fmt.Errorf("railspec: rule %q has invalid target/form arity", rule.ID)
		}
		seenTargets := map[string]bool{}
		for _, target := range rule.Targets {
			if targetNames[target] == "" || seenTargets[target] {
				return fmt.Errorf("railspec: rule %q has unknown or duplicate target %q", rule.ID, target)
			}
			seenTargets[target] = true
		}
		for _, form := range rule.Forms {
			if formNames[form] == "" {
				return fmt.Errorf("railspec: rule %q has unknown form %q", rule.ID, form)
			}
		}
		if rule.NativeBytes == 0 || rule.Latency == 0 || rule.Uops == 0 || !rule.Verified {
			return fmt.Errorf("railspec: rule %q lacks verified nonzero costs", rule.ID)
		}
	}
	return nil
}

func generate(spec contract) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by railspecgen; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package railspec")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type TargetMask uint8")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	fmt.Fprintln(&out, "\tTargetAMD64 TargetMask = 1 << iota")
	fmt.Fprintln(&out, "\tTargetARM64")
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type RuleID uint8")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	fmt.Fprintln(&out, "\tRuleInvalid RuleID = iota")
	for _, rule := range spec.Rules {
		fmt.Fprintf(&out, "\tRule%s\n", rule.GoName)
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type OperandForm uint8")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "const (")
	fmt.Fprintln(&out, "\tFormInvalid OperandForm = iota")
	for _, name := range []string{"Register", "SignedImm32", "FixedGPR1", "FixedGPR0", "UnsignedImm12", "Address", "Flags"} {
		fmt.Fprintf(&out, "\tForm%s\n", name)
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type Rule struct {")
	fmt.Fprintln(&out, "\tID RuleID")
	fmt.Fprintln(&out, "\tTargets TargetMask")
	fmt.Fprintln(&out, "\tNativeBytes uint8")
	fmt.Fprintln(&out, "\tLatency uint8")
	fmt.Fprintln(&out, "\tUops uint8")
	fmt.Fprintln(&out, "\tForms [3]OperandForm")
	fmt.Fprintln(&out, "\tFormCount uint8")
	fmt.Fprintln(&out, "\tVerified bool")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var Rules = [...]Rule{")
	fmt.Fprintln(&out, "\t{},")
	for _, rule := range spec.Rules {
		fmt.Fprintf(&out, "\t{ID: Rule%s, Targets: ", rule.GoName)
		for i, target := range rule.Targets {
			if i != 0 {
				fmt.Fprint(&out, " | ")
			}
			fmt.Fprint(&out, targetNames[target])
		}
		fmt.Fprintf(&out, ", NativeBytes: %d, Latency: %d, Uops: %d, Forms: [3]OperandForm{", rule.NativeBytes, rule.Latency, rule.Uops)
		for i, form := range rule.Forms {
			if i != 0 {
				fmt.Fprint(&out, ", ")
			}
			fmt.Fprint(&out, formNames[form])
		}
		fmt.Fprintf(&out, "}, FormCount: %d, Verified: true},\n", len(rule.Forms))
	}
	fmt.Fprintln(&out, "}")
	return format.Source(out.Bytes())
}

func failIf(err error) {
	if err == nil {
		return
	}
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
