// Command genfacade regenerates the root re-export facade (wago.go) from the
// exported identifiers of ./src/wago.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	implDir    = "src/wago"
	implAlias  = "impl"
	implImport = "github.com/wago-org/wago/src/wago"
	outFile    = "wago.go"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genfacade:", err)
		os.Exit(1)
	}
}

func run() error {
	var types, consts, valsAndFuncs []string

	entries, err := os.ReadDir(implDir)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(implDir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				// Methods ride along through their type alias; only top-level
				// functions need their own re-export.
				if d.Recv == nil && d.Name.IsExported() {
					valsAndFuncs = append(valsAndFuncs, d.Name.Name)
				}
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						if !s.Name.IsExported() {
							continue
						}
						if s.TypeParams != nil {
							// Pre-1.24 Go cannot alias an uninstantiated generic
							// type. None exist today; fail loudly if one appears.
							return fmt.Errorf("cannot re-export generic type %s: aliasing generics is unsupported", s.Name.Name)
						}
						types = append(types, s.Name.Name)
					case *ast.ValueSpec:
						for _, n := range s.Names {
							if !n.IsExported() {
								continue
							}
							if d.Tok == token.CONST {
								consts = append(consts, n.Name)
							} else {
								valsAndFuncs = append(valsAndFuncs, n.Name)
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(types)
	sort.Strings(consts)
	sort.Strings(valsAndFuncs)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/genfacade; DO NOT EDIT.\n\n")
	buf.WriteString("// Package wago exposes compile, instantiate, and run helpers for WebAssembly\n")
	buf.WriteString("// modules. It is a generated facade over the implementation in src/wago, so\n")
	buf.WriteString("// callers import the stable path \"github.com/wago-org/wago\" while the code\n")
	buf.WriteString("// lives under src/wago alongside the rest of the engine.\n")
	buf.WriteString("package wago\n\n")
	buf.WriteString("//go:generate go run ./internal/genfacade\n\n")
	fmt.Fprintf(&buf, "import %s %q\n\n", implAlias, implImport)

	// Type aliases keep the root and src/wago names identical types, so methods,
	// struct fields, and composite literals all carry over transparently.
	emitBlock(&buf, "type", types, implAlias)
	emitBlock(&buf, "const", consts, implAlias)
	// Functions and package-level vars re-export as value aliases; the compiler
	// rejects any signature or type drift against src/wago.
	emitBlock(&buf, "var", valsAndFuncs, implAlias)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n----\n%s", err, buf.Bytes())
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("genfacade: wrote %s (%d types, %d consts, %d funcs/vars)\n", outFile, len(types), len(consts), len(valsAndFuncs))
	return nil
}

func emitBlock(buf *bytes.Buffer, keyword string, names []string, alias string) {
	if len(names) == 0 {
		return
	}
	fmt.Fprintf(buf, "%s (\n", keyword)
	for _, n := range names {
		fmt.Fprintf(buf, "\t%s = %s.%s\n", n, alias, n)
	}
	buf.WriteString(")\n\n")
}
