// Command genfacade regenerates the root re-export facade (wago.go) from the
// exported identifiers of ./src/wago.
//
// The root package github.com/wago-org/wago is a thin facade so callers keep a
// clean import path while the implementation lives under src/wago. Go has no
// wildcard re-export, so this tool emits, per exported symbol:
//
//   - types as aliases (type X = impl.X), which carry methods and fields;
//   - constants as const X = impl.X;
//   - functions as forwarding wrappers (func X(...) ... { return impl.X(...) }),
//     so the root API stays real functions: proper godoc, no monkey-patching.
//
// Exported package-level vars are rejected: a `var X = impl.X` re-export would
// copy rather than alias, silently diverging from src/wago. None exist today.
//
// It is stdlib-only on purpose, to keep the root module free of dependencies.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	implDir    = "src/wago"
	implAlias  = "impl"
	implImport = "github.com/wago-org/wago/src/wago"
	outFile    = "wago.go"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genfacade:", err)
		os.Exit(1)
	}
}

func run() error {
	var types, consts []string
	var funcs []*ast.FuncDecl

	entries, err := os.ReadDir(implDir)
	if err != nil {
		return err
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(implDir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				// Methods ride along through their type alias; only top-level
				// functions need their own re-export.
				if d.Recv == nil && d.Name.IsExported() {
					funcs = append(funcs, d)
				}
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						if !s.Name.IsExported() {
							continue
						}
						if s.TypeParams != nil {
							// Pre-1.24 Go cannot alias an uninstantiated generic
							// type. None exist today; fail loudly if one appears.
							return fmt.Errorf("cannot re-export generic type %s: aliasing generics is unsupported", s.Name.Name)
						}
						types = append(types, s.Name.Name)
					case *ast.ValueSpec:
						for _, n := range s.Names {
							if !n.IsExported() {
								continue
							}
							if d.Tok != token.CONST {
								return fmt.Errorf("exported var %s in %s: genfacade cannot faithfully re-export a package var (a var alias would copy, not alias); re-export it deliberately by hand or avoid exporting it", n.Name, implDir)
							}
							consts = append(consts, n.Name)
						}
					}
				}
			}
		}
	}
	sort.Strings(types)
	sort.Strings(consts)
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].Name.Name < funcs[j].Name.Name })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by internal/genfacade; DO NOT EDIT.\n\n")
	buf.WriteString("// Package wago exposes compile, instantiate, and run helpers for WebAssembly\n")
	buf.WriteString("// modules. It is a generated facade over the implementation in src/wago, so\n")
	buf.WriteString("// callers import the stable path \"github.com/wago-org/wago\" while the code\n")
	buf.WriteString("// lives under src/wago alongside the rest of the engine.\n")
	buf.WriteString("package wago\n\n")
	buf.WriteString("//go:generate go run ./internal/genfacade\n\n")
	fmt.Fprintf(&buf, "import %s %q\n\n", implAlias, implImport)

	// Type aliases keep the root and src/wago names identical types, so methods,
	// struct fields, and composite literals all carry over transparently.
	emitConstLikeBlock(&buf, "type", types)
	emitConstLikeBlock(&buf, "const", consts)

	// Forwarding function wrappers. Signatures resolve through the type aliases
	// above, so godoc shows the same declarations as src/wago.
	for _, fn := range funcs {
		if err := emitFunc(&buf, fn); err != nil {
			return err
		}
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated source: %w\n----\n%s", err, buf.Bytes())
	}
	if err := os.WriteFile(outFile, src, 0o644); err != nil {
		return err
	}
	fmt.Printf("genfacade: wrote %s (%d types, %d consts, %d funcs)\n", outFile, len(types), len(consts), len(funcs))
	return nil
}

func emitConstLikeBlock(buf *bytes.Buffer, keyword string, names []string) {
	if len(names) == 0 {
		return
	}
	fmt.Fprintf(buf, "%s (\n", keyword)
	for _, n := range names {
		fmt.Fprintf(buf, "\t%s = %s.%s\n", n, implAlias, n)
	}
	buf.WriteString(")\n\n")
}

func emitFunc(buf *bytes.Buffer, fn *ast.FuncDecl) error {
	var params, args []string
	idx := 0
	if fn.Type.Params != nil {
		for _, field := range fn.Type.Params.List {
			typeStr, err := renderType(field.Type)
			if err != nil {
				return fmt.Errorf("func %s: %w", fn.Name.Name, err)
			}
			_, variadic := field.Type.(*ast.Ellipsis)
			names := field.Names
			if len(names) == 0 {
				names = []*ast.Ident{nil} // one unnamed param slot
			}
			for _, nm := range names {
				pname := fmt.Sprintf("p%d", idx)
				if nm != nil && nm.Name != "" && nm.Name != "_" {
					pname = nm.Name
				}
				idx++
				params = append(params, pname+" "+typeStr)
				if variadic {
					args = append(args, pname+"...")
				} else {
					args = append(args, pname)
				}
			}
		}
	}

	var resultStr string
	hasResults := fn.Type.Results != nil && len(fn.Type.Results.List) > 0
	if hasResults {
		var rs []string
		for _, field := range fn.Type.Results.List {
			ts, err := renderType(field.Type)
			if err != nil {
				return fmt.Errorf("func %s result: %w", fn.Name.Name, err)
			}
			count := len(field.Names)
			if count == 0 {
				count = 1
			}
			for i := 0; i < count; i++ {
				rs = append(rs, ts)
			}
		}
		if len(rs) == 1 {
			resultStr = " " + rs[0]
		} else {
			resultStr = " (" + strings.Join(rs, ", ") + ")"
		}
	}

	call := implAlias + "." + fn.Name.Name + "(" + strings.Join(args, ", ") + ")"
	body := call
	if hasResults {
		body = "return " + call
	}
	fmt.Fprintf(buf, "func %s(%s)%s { %s }\n\n", fn.Name.Name, strings.Join(params, ", "), resultStr, body)
	return nil
}

// renderType prints a type expression as it should appear in the facade. Bare
// exported identifiers refer to src/wago types that have a root alias, so they
// stay unqualified (godoc reads identically); predeclared names stay as-is.
// Anything that would need an extra import or special handling fails loudly.
func renderType(expr ast.Expr) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name, nil // exported -> root alias; predeclared (byte, error, ...) -> itself
	case *ast.StarExpr:
		inner, err := renderType(t.X)
		if err != nil {
			return "", err
		}
		return "*" + inner, nil
	case *ast.ArrayType:
		elt, err := renderType(t.Elt)
		if err != nil {
			return "", err
		}
		if t.Len == nil {
			return "[]" + elt, nil
		}
		lit, ok := t.Len.(*ast.BasicLit)
		if !ok {
			return "", fmt.Errorf("unsupported array length expression %T", t.Len)
		}
		return "[" + lit.Value + "]" + elt, nil
	case *ast.Ellipsis:
		elt, err := renderType(t.Elt)
		if err != nil {
			return "", err
		}
		return "..." + elt, nil
	case *ast.MapType:
		k, err := renderType(t.Key)
		if err != nil {
			return "", err
		}
		v, err := renderType(t.Value)
		if err != nil {
			return "", err
		}
		return "map[" + k + "]" + v, nil
	case *ast.InterfaceType:
		if t.Methods == nil || len(t.Methods.List) == 0 {
			return "interface{}", nil
		}
		return "", fmt.Errorf("non-empty interface type is unsupported")
	default:
		return "", fmt.Errorf("unsupported type expression %T in a public signature; genfacade needs extending (external-package or func types require import handling)", expr)
	}
}
