// Code generated by internal/genfacade; DO NOT EDIT.

// Package wago exposes compile, instantiate, and run helpers for WebAssembly
// modules. It is a generated facade over the implementation in src/wago, so
// callers import the stable path "github.com/wago-org/wago" while the code
// lives under src/wago alongside the rest of the engine.
package wago

//go:generate go run ./internal/genfacade

import impl "github.com/wago-org/wago/src/wago"

type (
	AbstractHeapType           = impl.AbstractHeapType
	ArtifactLimits             = impl.ArtifactLimits
	ArtifactSectionSizes       = impl.ArtifactSectionSizes
	Bits                       = impl.Bits
	BoundsCheckMode            = impl.BoundsCheckMode
	CallerResolver             = impl.CallerResolver
	Capability                 = impl.Capability
	CapabilityBudget           = impl.CapabilityBudget
	CapabilityOption           = impl.CapabilityOption
	Compatibility              = impl.Compatibility
	CompileContext             = impl.CompileContext
	CompileHookAccess          = impl.CompileHookAccess
	Compiled                   = impl.Compiled
	CompilerRegistry           = impl.CompilerRegistry
	CompositeTypeKind          = impl.CompositeTypeKind
	ConfigSchemaProvider       = impl.ConfigSchemaProvider
	CoreFeatures               = impl.CoreFeatures
	CoreRuntime                = impl.CoreRuntime
	CoreRuntimeAccess          = impl.CoreRuntimeAccess
	CustomSignature            = impl.CustomSignature
	CustomType                 = impl.CustomType
	CustomTypeSpec             = impl.CustomTypeSpec
	DataInit                   = impl.DataInit
	DefinedTypeDescriptor      = impl.DefinedTypeDescriptor
	Dirs                       = impl.Dirs
	ElemInit                   = impl.ElemInit
	ElemMode                   = impl.ElemMode
	ExitError                  = impl.ExitError
	Extension                  = impl.Extension
	ExtensionError             = impl.ExtensionError
	ExtensionFactory           = impl.ExtensionFactory
	ExtensionInfo              = impl.ExtensionInfo
	ExternRef                  = impl.ExternRef
	ExternRefHostModule        = impl.ExternRefHostModule
	FeatureInfo                = impl.FeatureInfo
	FieldTypeDescriptor        = impl.FieldTypeDescriptor
	FuncRef                    = impl.FuncRef
	FuncSig                    = impl.FuncSig
	FunctionMetadata           = impl.FunctionMetadata
	GCAllocatorKind            = impl.GCAllocatorKind
	GCBenchmarkConfiguration   = impl.GCBenchmarkConfiguration
	GCBenchmarkTelemetryReport = impl.GCBenchmarkTelemetryReport
	GCConfig                   = impl.GCConfig
	GCHelperStats              = impl.GCHelperStats
	GCHostModule               = impl.GCHostModule
	GCManagedHeapTelemetry     = impl.GCManagedHeapTelemetry
	GCMemoryDomains            = impl.GCMemoryDomains
	GCNativeCodeTelemetry      = impl.GCNativeCodeTelemetry
	GCNativeRootAdmission      = impl.GCNativeRootAdmission
	GCProfile                  = impl.GCProfile
	GCRef                      = impl.GCRef
	GCRuntimeKind              = impl.GCRuntimeKind
	GCTelemetry                = impl.GCTelemetry
	GCTelemetrySnapshot        = impl.GCTelemetrySnapshot
	Global                     = impl.Global
	GlobalDef                  = impl.GlobalDef
	GlobalImport               = impl.GlobalImport
	GlobalImportDef            = impl.GlobalImportDef
	GlobalMetadata             = impl.GlobalMetadata
	GuardPageUnavailableError  = impl.GuardPageUnavailableError
	Handle                     = impl.Handle
	HandleTable                = impl.HandleTable
	HeapTypeDescriptor         = impl.HeapTypeDescriptor
	HookRegistry               = impl.HookRegistry
	HostEnvironment            = impl.HostEnvironment
	HostExit                   = impl.HostExit
	HostFunc                   = impl.HostFunc
	HostFuncRef                = impl.HostFuncRef
	HostImportAccess           = impl.HostImportAccess
	HostModule                 = impl.HostModule
	HostTrap                   = impl.HostTrap
	I31Ref                     = impl.I31Ref
	ImportFuncBuilder          = impl.ImportFuncBuilder
	ImportKind                 = impl.ImportKind
	ImportModuleBuilder        = impl.ImportModuleBuilder
	ImportOverridePolicy       = impl.ImportOverridePolicy
	ImportSpec                 = impl.ImportSpec
	Imports                    = impl.Imports
	Instance                   = impl.Instance
	InstanceContext            = impl.InstanceContext
	InstanceExport             = impl.InstanceExport
	InstanceHookAccess         = impl.InstanceHookAccess
	InstanceManager            = impl.InstanceManager
	Instantiable               = impl.Instantiable
	InstantiateContext         = impl.InstantiateContext
	InstantiateOption          = impl.InstantiateOption
	InstantiateOptions         = impl.InstantiateOptions
	InstantiateOrigin          = impl.InstantiateOrigin
	InstructionContext         = impl.InstructionContext
	InstructionHandler         = impl.InstructionHandler
	InstructionLowerer         = impl.InstructionLowerer
	InstructionSpec            = impl.InstructionSpec
	InvokeContext              = impl.InvokeContext
	InvokeHookAccess           = impl.InvokeHookAccess
	LowerValue                 = impl.LowerValue
	LoweringContext            = impl.LoweringContext
	ManagedInstance            = impl.ManagedInstance
	Memory                     = impl.Memory
	MemoryMetadata             = impl.MemoryMetadata
	Module                     = impl.Module
	ModuleMetadata             = impl.ModuleMetadata
	OffsetInit                 = impl.OffsetInit
	OptKnobInfo                = impl.OptKnobInfo
	PackedType                 = impl.PackedType
	PassiveDataInit            = impl.PassiveDataInit
	PluginCapability           = impl.PluginCapability
	PluginConfig               = impl.PluginConfig
	PluginError                = impl.PluginError
	PluginHost                 = impl.PluginHost
	PluginPhase                = impl.PluginPhase
	PluginPlan                 = impl.PluginPlan
	PluginPlanEntry            = impl.PluginPlanEntry
	PluginStarter              = impl.PluginStarter
	PluginStopper              = impl.PluginStopper
	Policy                     = impl.Policy
	PreparedFunction           = impl.PreparedFunction
	RefInit                    = impl.RefInit
	ReferenceTypeDescriptor    = impl.ReferenceTypeDescriptor
	Registry                   = impl.Registry
	Resource                   = impl.Resource
	Runtime                    = impl.Runtime
	RuntimeConfig              = impl.RuntimeConfig
	RuntimeContext             = impl.RuntimeContext
	RuntimeHookAccess          = impl.RuntimeHookAccess
	RuntimeOption              = impl.RuntimeOption
	ServiceRef                 = impl.ServiceRef
	Stability                  = impl.Stability
	StorageTypeDescriptor      = impl.StorageTypeDescriptor
	Table                      = impl.Table
	TableMetadata              = impl.TableMetadata
	Tag                        = impl.Tag
	TagMetadata                = impl.TagMetadata
	TrapCode                   = impl.TrapCode
	TrapError                  = impl.TrapError
	TrapFrame                  = impl.TrapFrame
	UnsupportedFeatureError    = impl.UnsupportedFeatureError
	UseOption                  = impl.UseOption
	V128                       = impl.V128
	ValType                    = impl.ValType
	Value                      = impl.Value
	ValueTypeDescriptor        = impl.ValueTypeDescriptor
	ValueTypeKind              = impl.ValueTypeKind
	WasmType                   = impl.WasmType
)

const (
	AbstractHeapAny                            = impl.AbstractHeapAny
	AbstractHeapArray                          = impl.AbstractHeapArray
	AbstractHeapEq                             = impl.AbstractHeapEq
	AbstractHeapExn                            = impl.AbstractHeapExn
	AbstractHeapExtern                         = impl.AbstractHeapExtern
	AbstractHeapFunc                           = impl.AbstractHeapFunc
	AbstractHeapI31                            = impl.AbstractHeapI31
	AbstractHeapNoExn                          = impl.AbstractHeapNoExn
	AbstractHeapNoExtern                       = impl.AbstractHeapNoExtern
	AbstractHeapNoFunc                         = impl.AbstractHeapNoFunc
	AbstractHeapNone                           = impl.AbstractHeapNone
	AbstractHeapString                         = impl.AbstractHeapString
	AbstractHeapStruct                         = impl.AbstractHeapStruct
	AllowTestOverrides                         = impl.AllowTestOverrides
	BoundsChecksExplicit                       = impl.BoundsChecksExplicit
	BoundsChecksSignalsBased                   = impl.BoundsChecksSignalsBased
	CapCompilerCodegen                         = impl.CapCompilerCodegen
	CapFilesystemRead                          = impl.CapFilesystemRead
	CapFilesystemWrite                         = impl.CapFilesystemWrite
	CapHTTPClient                              = impl.CapHTTPClient
	CapKVRead                                  = impl.CapKVRead
	CapKVWrite                                 = impl.CapKVWrite
	CapMetricsWrite                            = impl.CapMetricsWrite
	CapNetworkOutbound                         = impl.CapNetworkOutbound
	CapTimerRead                               = impl.CapTimerRead
	CompositeTypeArray                         = impl.CompositeTypeArray
	CompositeTypeFunction                      = impl.CompositeTypeFunction
	CompositeTypeStruct                        = impl.CompositeTypeStruct
	CoreFeatureBulkMemoryOperations            = impl.CoreFeatureBulkMemoryOperations
	CoreFeatureExceptionHandling               = impl.CoreFeatureExceptionHandling
	CoreFeatureExtendedConst                   = impl.CoreFeatureExtendedConst
	CoreFeatureExtendedConstExpressions        = impl.CoreFeatureExtendedConstExpressions
	CoreFeatureGC                              = impl.CoreFeatureGC
	CoreFeatureMemory64                        = impl.CoreFeatureMemory64
	CoreFeatureMultiMemory                     = impl.CoreFeatureMultiMemory
	CoreFeatureMultiValue                      = impl.CoreFeatureMultiValue
	CoreFeatureMutableGlobal                   = impl.CoreFeatureMutableGlobal
	CoreFeatureNonTrappingFloatToIntConversion = impl.CoreFeatureNonTrappingFloatToIntConversion
	CoreFeatureReferenceTypes                  = impl.CoreFeatureReferenceTypes
	CoreFeatureSIMD                            = impl.CoreFeatureSIMD
	CoreFeatureSignExtensionOps                = impl.CoreFeatureSignExtensionOps
	CoreFeatureTable64                         = impl.CoreFeatureTable64
	CoreFeatureTailCall                        = impl.CoreFeatureTailCall
	CoreFeatureThreads                         = impl.CoreFeatureThreads
	CoreFeatureTypedFunctionReferences         = impl.CoreFeatureTypedFunctionReferences
	CoreFeaturesV1                             = impl.CoreFeaturesV1
	CoreFeaturesV2                             = impl.CoreFeaturesV2
	CoreFeaturesV3                             = impl.CoreFeaturesV3
	Deprecated                                 = impl.Deprecated
	ElemModeActive                             = impl.ElemModeActive
	ElemModeDeclarative                        = impl.ElemModeDeclarative
	ElemModePassive                            = impl.ElemModePassive
	ErrCallbackPanic                           = impl.ErrCallbackPanic
	ErrExtensionConflict                       = impl.ErrExtensionConflict
	ErrForeignModule                           = impl.ErrForeignModule
	ErrInvalidHandle                           = impl.ErrInvalidHandle
	ErrManagedImportLifetime                   = impl.ErrManagedImportLifetime
	ErrMissingImport                           = impl.ErrMissingImport
	ErrPermissionDenied                        = impl.ErrPermissionDenied
	Experimental                               = impl.Experimental
	GCAllocatorPagedSizeClass                  = impl.GCAllocatorPagedSizeClass
	GCAllocatorTinyFixedBlock                  = impl.GCAllocatorTinyFixedBlock
	GCProfileThroughput                        = impl.GCProfileThroughput
	GCProfileTiny                              = impl.GCProfileTiny
	GCRuntimeGenerational                      = impl.GCRuntimeGenerational
	GCRuntimeIncrementalMarkSweep              = impl.GCRuntimeIncrementalMarkSweep
	GCTelemetrySchemaVersion                   = impl.GCTelemetrySchemaVersion
	ImportFunc                                 = impl.ImportFunc
	ImportGlobal                               = impl.ImportGlobal
	ImportMemory                               = impl.ImportMemory
	ImportTable                                = impl.ImportTable
	ImportTag                                  = impl.ImportTag
	InstantiateDirect                          = impl.InstantiateDirect
	InstantiateManaged                         = impl.InstantiateManaged
	NoExtensionOverrides                       = impl.NoExtensionOverrides
	PackedTypeI16                              = impl.PackedTypeI16
	PackedTypeI8                               = impl.PackedTypeI8
	PluginCompileHooks                         = impl.PluginCompileHooks
	PluginCoreRuntime                          = impl.PluginCoreRuntime
	PluginHostEnvironment                      = impl.PluginHostEnvironment
	PluginHostImports                          = impl.PluginHostImports
	PluginInstanceHooks                        = impl.PluginInstanceHooks
	PluginInvokeHooks                          = impl.PluginInvokeHooks
	PluginManagedInstances                     = impl.PluginManagedInstances
	PluginPhaseAuthorize                       = impl.PluginPhaseAuthorize
	PluginPhaseConfigure                       = impl.PluginPhaseConfigure
	PluginPhaseRegister                        = impl.PluginPhaseRegister
	PluginPhaseResolve                         = impl.PluginPhaseResolve
	PluginPhaseStart                           = impl.PluginPhaseStart
	PluginPhaseStop                            = impl.PluginPhaseStop
	PluginRuntimeHooks                         = impl.PluginRuntimeHooks
	Stable                                     = impl.Stable
	TrapAtomicUnaligned                        = impl.TrapAtomicUnaligned
	TrapBuiltin                                = impl.TrapBuiltin
	TrapCalledFnNotLinked                      = impl.TrapCalledFnNotLinked
	TrapCastFailure                            = impl.TrapCastFailure
	TrapDivOverflow                            = impl.TrapDivOverflow
	TrapDivZero                                = impl.TrapDivZero
	TrapIndirectOutOfBounds                    = impl.TrapIndirectOutOfBounds
	TrapIndirectWrongSig                       = impl.TrapIndirectWrongSig
	TrapInterrupted                            = impl.TrapInterrupted
	TrapLinMemCouldNotExtend                   = impl.TrapLinMemCouldNotExtend
	TrapLinMemOutOfBounds                      = impl.TrapLinMemOutOfBounds
	TrapLinkedMemNotLinked                     = impl.TrapLinkedMemNotLinked
	TrapLinkedMemOutOfBounds                   = impl.TrapLinkedMemOutOfBounds
	TrapNone                                   = impl.TrapNone
	TrapNullReference                          = impl.TrapNullReference
	TrapStackFenceBreached                     = impl.TrapStackFenceBreached
	TrapTableOutOfBounds                       = impl.TrapTableOutOfBounds
	TrapTruncOverflow                          = impl.TrapTruncOverflow
	TrapUnhandledException                     = impl.TrapUnhandledException
	TrapUnreachable                            = impl.TrapUnreachable
	ValAnyRef                                  = impl.ValAnyRef
	ValExnRef                                  = impl.ValExnRef
	ValExternRef                               = impl.ValExternRef
	ValF32                                     = impl.ValF32
	ValF64                                     = impl.ValF64
	ValFuncRef                                 = impl.ValFuncRef
	ValI31Ref                                  = impl.ValI31Ref
	ValI32                                     = impl.ValI32
	ValI64                                     = impl.ValI64
	ValV128                                    = impl.ValV128
	ValueTypeF32                               = impl.ValueTypeF32
	ValueTypeF64                               = impl.ValueTypeF64
	ValueTypeI32                               = impl.ValueTypeI32
	ValueTypeI64                               = impl.ValueTypeI64
	ValueTypeReference                         = impl.ValueTypeReference
	ValueTypeV128                              = impl.ValueTypeV128
	Version                                    = impl.Version
	WasmExternRef                              = impl.WasmExternRef
	WasmF32                                    = impl.WasmF32
	WasmF64                                    = impl.WasmF64
	WasmFuncRef                                = impl.WasmFuncRef
	WasmI32                                    = impl.WasmI32
	WasmI64                                    = impl.WasmI64
	WasmV128                                   = impl.WasmV128
)

func AsF32(b uint64) float32 { return impl.AsF32(b) }

func AsF64(b uint64) float64 { return impl.AsF64(b) }

func AsI32(b uint64) int32 { return impl.AsI32(b) }

func AsI64(b uint64) int64 { return impl.AsI64(b) }

func BitsFromUint32(width int32, value uint32) (Bits, error) {
	return impl.BitsFromUint32(width, value)
}

func CapabilityDocs(docs string) CapabilityOption { return impl.CapabilityDocs(docs) }

func CaptureGCMemoryDomains(compilerHeapBytes uint64, executableJITBytes uint64, heap GCManagedHeapTelemetry) GCMemoryDomains {
	return impl.CaptureGCMemoryDomains(compilerHeapBytes, executableJITBytes, heap)
}

func Compile(args ...any) (*Compiled, error) { return impl.Compile(args...) }

func CompileWithConfig(cfg *RuntimeConfig, wasmBytes []byte) (*Compiled, error) {
	return impl.CompileWithConfig(cfg, wasmBytes)
}

func DefaultArtifactLimits() ArtifactLimits { return impl.DefaultArtifactLimits() }

func DirsFor(version string) Dirs { return impl.DirsFor(version) }

func F32(v float32) uint64 { return impl.F32(v) }

func F64(v float64) uint64 { return impl.F64(v) }

func FeatureInfoByName(name string) (FeatureInfo, bool) { return impl.FeatureInfoByName(name) }

func FeatureInfos() []FeatureInfo { return impl.FeatureInfos() }

func GCTelemetryAvailable() bool { return impl.GCTelemetryAvailable() }

func GuardPageSupported() bool { return impl.GuardPageSupported() }

func GuestArgs() []string { return impl.GuestArgs() }

func I32(v int32) uint64 { return impl.I32(v) }

func I64(v int64) uint64 { return impl.I64(v) }

func InspectPluginPlan(configs []PluginConfig) (*PluginPlan, error) {
	return impl.InspectPluginPlan(configs)
}

func Instantiate(source Instantiable, opts ...any) (*Instance, error) {
	return impl.Instantiate(source, opts...)
}

func IsCompiled(b []byte) bool { return impl.IsCompiled(b) }

func IsGuardPageUnavailable(err error) bool { return impl.IsGuardPageUnavailable(err) }

func Load(b []byte) (*Compiled, error) { return impl.Load(b) }

func MustCompile(wasmBytes []byte) *Compiled { return impl.MustCompile(wasmBytes) }

func NewBits(width int32, littleEndian []byte) (Bits, error) {
	return impl.NewBits(width, littleEndian)
}

func NewExtension(name string) (Extension, bool) { return impl.NewExtension(name) }

func NewGCBenchmarkTelemetryReport(name string) GCBenchmarkTelemetryReport {
	return impl.NewGCBenchmarkTelemetryReport(name)
}

func NewGlobalF32(v float32, mutable bool) *Global { return impl.NewGlobalF32(v, mutable) }

func NewGlobalF64(v float64, mutable bool) *Global { return impl.NewGlobalF64(v, mutable) }

func NewGlobalI32(v int32, mutable bool) *Global { return impl.NewGlobalI32(v, mutable) }

func NewGlobalI64(v int64, mutable bool) *Global { return impl.NewGlobalI64(v, mutable) }

func NewGlobalV128(v V128, mutable bool) *Global { return impl.NewGlobalV128(v, mutable) }

func NewHandleTable() *HandleTable { return impl.NewHandleTable() }

func NewI31Ref(v int32) I31Ref { return impl.NewI31Ref(v) }

func NewMemory(minPages uint32, maxPages uint32) (*Memory, error) {
	return impl.NewMemory(minPages, maxPages)
}

func NewRuntime(opts ...RuntimeOption) *Runtime { return impl.NewRuntime(opts...) }

func NewRuntimeConfig() *RuntimeConfig { return impl.NewRuntimeConfig() }

func NewSharedMemory(minPages uint32, maxPages uint32) (*Memory, error) {
	return impl.NewSharedMemory(minPages, maxPages)
}

func NewTable(minSize uint32, maxSize uint32) (*Table, error) { return impl.NewTable(minSize, maxSize) }

func NewTable64(minSize uint32, maxSize uint32) (*Table, error) {
	return impl.NewTable64(minSize, maxSize)
}

func NullExternRef() ExternRef { return impl.NullExternRef() }

func NullFuncRef() FuncRef { return impl.NullFuncRef() }

func NullGCRef() GCRef { return impl.NullGCRef() }

func NullI31Ref() I31Ref { return impl.NullI31Ref() }

func OptKnobs() []OptKnobInfo { return impl.OptKnobs() }

func OptimizationInfos() []OptKnobInfo { return impl.OptimizationInfos() }

func OptimizationInfosForArch(arch string) []OptKnobInfo { return impl.OptimizationInfosForArch(arch) }

func ProvideService(reg *Registry, name string, value any) error {
	return impl.ProvideService(reg, name, value)
}

func RegisterExtension(name string, factory ExtensionFactory) { impl.RegisterExtension(name, factory) }

func RegisteredPluginNames() []string { return impl.RegisteredPluginNames() }

func RequireService(reg *Registry, name string, typeWitness ...any) (*ServiceRef, error) {
	return impl.RequireService(reg, name, typeWitness...)
}

func SetGuestArgs(args []string) { impl.SetGuestArgs(args) }

func SetOptKnob(name string, on bool) bool { return impl.SetOptKnob(name, on) }

func SupportedFeatures() CoreFeatures { return impl.SupportedFeatures() }

func ValueExternRef(v ExternRef) Value { return impl.ValueExternRef(v) }

func ValueF32(v float32) Value { return impl.ValueF32(v) }

func ValueF64(v float64) Value { return impl.ValueF64(v) }

func ValueFuncRef(v FuncRef) Value { return impl.ValueFuncRef(v) }

func ValueGCRef(v GCRef) Value { return impl.ValueGCRef(v) }

func ValueI31Ref(v I31Ref) Value { return impl.ValueI31Ref(v) }

func ValueI32(v int32) Value { return impl.ValueI32(v) }

func ValueI64(v int64) Value { return impl.ValueI64(v) }

func ValueOf(t ValType, bits uint64) Value { return impl.ValueOf(t, bits) }

func WithGC(gc GCConfig) InstantiateOption { return impl.WithGC(gc) }

func WithImportOverridePolicy(p ImportOverridePolicy) RuntimeOption {
	return impl.WithImportOverridePolicy(p)
}

func WithImports(im Imports) InstantiateOption { return impl.WithImports(im) }

func WithPluginGrants(caps ...PluginCapability) UseOption { return impl.WithPluginGrants(caps...) }

func WithPolicy(p Policy) InstantiateOption { return impl.WithPolicy(p) }

func WithRuntimeConfig(cfg *RuntimeConfig) RuntimeOption { return impl.WithRuntimeConfig(cfg) }

func WithSynchronousHostCalls() InstantiateOption { return impl.WithSynchronousHostCalls() }
