// Code generated by internal/genfacade; DO NOT EDIT.

// Package wago exposes compile, instantiate, and run helpers for WebAssembly
// modules. It is a generated facade over the implementation in src/wago, so
// callers import the stable path "github.com/wago-org/wago" while the code
// lives under src/wago alongside the rest of the engine.
package wago

//go:generate go run ./internal/genfacade

import impl "github.com/wago-org/wago/src/wago"

type (
	BoundsCheckMode           = impl.BoundsCheckMode
	Capability                = impl.Capability
	CapabilityOption          = impl.CapabilityOption
	ChildSpec                 = impl.ChildSpec
	Class                     = impl.Class
	ClassOptions              = impl.ClassOptions
	Compatibility             = impl.Compatibility
	CompileContext            = impl.CompileContext
	Compiled                  = impl.Compiled
	CoreFeatures              = impl.CoreFeatures
	DataInit                  = impl.DataInit
	Dirs                      = impl.Dirs
	ElemInit                  = impl.ElemInit
	ElemMode                  = impl.ElemMode
	ExitError                 = impl.ExitError
	ExitEvent                 = impl.ExitEvent
	ExitReason                = impl.ExitReason
	Extension                 = impl.Extension
	ExtensionError            = impl.ExtensionError
	ExtensionFactory          = impl.ExtensionFactory
	ExtensionInfo             = impl.ExtensionInfo
	ExternRef                 = impl.ExternRef
	ExternRefHostModule       = impl.ExternRefHostModule
	FuncRef                   = impl.FuncRef
	FuncSig                   = impl.FuncSig
	GCAllocatorKind           = impl.GCAllocatorKind
	GCConfig                  = impl.GCConfig
	GCProfile                 = impl.GCProfile
	GCRuntimeKind             = impl.GCRuntimeKind
	Global                    = impl.Global
	GlobalDef                 = impl.GlobalDef
	GlobalImport              = impl.GlobalImport
	GlobalImportDef           = impl.GlobalImportDef
	GuardPageUnavailableError = impl.GuardPageUnavailableError
	Handle                    = impl.Handle
	HandleTable               = impl.HandleTable
	HookRegistry              = impl.HookRegistry
	HostExit                  = impl.HostExit
	HostFunc                  = impl.HostFunc
	HostModule                = impl.HostModule
	ImportFuncBuilder         = impl.ImportFuncBuilder
	ImportKind                = impl.ImportKind
	ImportModuleBuilder       = impl.ImportModuleBuilder
	ImportOverridePolicy      = impl.ImportOverridePolicy
	ImportSpec                = impl.ImportSpec
	Imports                   = impl.Imports
	Instance                  = impl.Instance
	InstanceExport            = impl.InstanceExport
	InstancePool              = impl.InstancePool
	Instantiable              = impl.Instantiable
	InstantiateContext        = impl.InstantiateContext
	InstantiateOption         = impl.InstantiateOption
	InstantiateOptions        = impl.InstantiateOptions
	InvokeContext             = impl.InvokeContext
	Lease                     = impl.Lease
	Mailbox                   = impl.Mailbox
	Memory                    = impl.Memory
	Module                    = impl.Module
	ModuleMetadata            = impl.ModuleMetadata
	OffsetInit                = impl.OffsetInit
	PID                       = impl.PID
	PassiveDataInit           = impl.PassiveDataInit
	Policy                    = impl.Policy
	PoolOptions               = impl.PoolOptions
	PoolStats                 = impl.PoolStats
	Process                   = impl.Process
	RefInit                   = impl.RefInit
	Registry                  = impl.Registry
	ResetPolicy               = impl.ResetPolicy
	Resource                  = impl.Resource
	RestartPolicy             = impl.RestartPolicy
	RestartStrategy           = impl.RestartStrategy
	Runtime                   = impl.Runtime
	RuntimeConfig             = impl.RuntimeConfig
	RuntimeContext            = impl.RuntimeContext
	RuntimeOption             = impl.RuntimeOption
	Snapshot                  = impl.Snapshot
	SnapshotKind              = impl.SnapshotKind
	SnapshotLease             = impl.SnapshotLease
	SnapshotOptions           = impl.SnapshotOptions
	SnapshotPoolOptions       = impl.SnapshotPoolOptions
	SpawnOptions              = impl.SpawnOptions
	Stability                 = impl.Stability
	Supervisor                = impl.Supervisor
	SupervisorOptions         = impl.SupervisorOptions
	Table                     = impl.Table
	TrapCode                  = impl.TrapCode
	TrapError                 = impl.TrapError
	UnsupportedFeatureError   = impl.UnsupportedFeatureError
	UseOption                 = impl.UseOption
	V128                      = impl.V128
	ValType                   = impl.ValType
	Value                     = impl.Value
)

const (
	AllowTestOverrides                         = impl.AllowTestOverrides
	BoundsChecksExplicit                       = impl.BoundsChecksExplicit
	BoundsChecksSignalsBased                   = impl.BoundsChecksSignalsBased
	CapCompilerCodegen                         = impl.CapCompilerCodegen
	CapFilesystemRead                          = impl.CapFilesystemRead
	CapFilesystemWrite                         = impl.CapFilesystemWrite
	CapHTTPClient                              = impl.CapHTTPClient
	CapKVRead                                  = impl.CapKVRead
	CapKVWrite                                 = impl.CapKVWrite
	CapMailboxReceive                          = impl.CapMailboxReceive
	CapMailboxSend                             = impl.CapMailboxSend
	CapMetricsWrite                            = impl.CapMetricsWrite
	CapNetworkOutbound                         = impl.CapNetworkOutbound
	CapProcessKill                             = impl.CapProcessKill
	CapProcessSpawn                            = impl.CapProcessSpawn
	CapTimerRead                               = impl.CapTimerRead
	CapWASI                                    = impl.CapWASI
	CoreFeatureBulkMemoryOperations            = impl.CoreFeatureBulkMemoryOperations
	CoreFeatureMultiValue                      = impl.CoreFeatureMultiValue
	CoreFeatureMutableGlobal                   = impl.CoreFeatureMutableGlobal
	CoreFeatureNonTrappingFloatToIntConversion = impl.CoreFeatureNonTrappingFloatToIntConversion
	CoreFeatureReferenceTypes                  = impl.CoreFeatureReferenceTypes
	CoreFeatureSIMD                            = impl.CoreFeatureSIMD
	CoreFeatureSignExtensionOps                = impl.CoreFeatureSignExtensionOps
	CoreFeatureTailCall                        = impl.CoreFeatureTailCall
	CoreFeaturesV1                             = impl.CoreFeaturesV1
	CoreFeaturesV2                             = impl.CoreFeaturesV2
	DefaultMailboxCapacity                     = impl.DefaultMailboxCapacity
	Deprecated                                 = impl.Deprecated
	ElemModeActive                             = impl.ElemModeActive
	ElemModeDeclarative                        = impl.ElemModeDeclarative
	ElemModePassive                            = impl.ElemModePassive
	ErrExtensionConflict                       = impl.ErrExtensionConflict
	ErrInvalidHandle                           = impl.ErrInvalidHandle
	ErrMailboxClosed                           = impl.ErrMailboxClosed
	ErrMailboxFull                             = impl.ErrMailboxFull
	ErrMissingImport                           = impl.ErrMissingImport
	ErrNoProcess                               = impl.ErrNoProcess
	ErrPermissionDenied                        = impl.ErrPermissionDenied
	Experimental                               = impl.Experimental
	GCAllocatorPagedSizeClass                  = impl.GCAllocatorPagedSizeClass
	GCAllocatorTinyFixedBlock                  = impl.GCAllocatorTinyFixedBlock
	GCProfileThroughput                        = impl.GCProfileThroughput
	GCProfileTiny                              = impl.GCProfileTiny
	GCRuntimeGenerational                      = impl.GCRuntimeGenerational
	GCRuntimeIncrementalMarkSweep              = impl.GCRuntimeIncrementalMarkSweep
	ImportFunc                                 = impl.ImportFunc
	ImportGlobal                               = impl.ImportGlobal
	ImportMemory                               = impl.ImportMemory
	ImportTable                                = impl.ImportTable
	NoExtensionOverrides                       = impl.NoExtensionOverrides
	OneForAll                                  = impl.OneForAll
	OneForOne                                  = impl.OneForOne
	ResetCopyOnWrite                           = impl.ResetCopyOnWrite
	ResetMemorySnapshot                        = impl.ResetMemorySnapshot
	ResetReinstantiate                         = impl.ResetReinstantiate
	RestartPermanent                           = impl.RestartPermanent
	RestartTemporary                           = impl.RestartTemporary
	RestartTransient                           = impl.RestartTransient
	SnapshotInit                               = impl.SnapshotInit
	SnapshotWarm                               = impl.SnapshotWarm
	Stable                                     = impl.Stable
	TrapBuiltin                                = impl.TrapBuiltin
	TrapCalledFnNotLinked                      = impl.TrapCalledFnNotLinked
	TrapDivOverflow                            = impl.TrapDivOverflow
	TrapDivZero                                = impl.TrapDivZero
	TrapIndirectOutOfBounds                    = impl.TrapIndirectOutOfBounds
	TrapIndirectWrongSig                       = impl.TrapIndirectWrongSig
	TrapInterrupted                            = impl.TrapInterrupted
	TrapLinMemCouldNotExtend                   = impl.TrapLinMemCouldNotExtend
	TrapLinMemOutOfBounds                      = impl.TrapLinMemOutOfBounds
	TrapLinkedMemNotLinked                     = impl.TrapLinkedMemNotLinked
	TrapLinkedMemOutOfBounds                   = impl.TrapLinkedMemOutOfBounds
	TrapNone                                   = impl.TrapNone
	TrapStackFenceBreached                     = impl.TrapStackFenceBreached
	TrapTruncOverflow                          = impl.TrapTruncOverflow
	TrapUnreachable                            = impl.TrapUnreachable
	ValExternRef                               = impl.ValExternRef
	ValF32                                     = impl.ValF32
	ValF64                                     = impl.ValF64
	ValFuncRef                                 = impl.ValFuncRef
	ValI32                                     = impl.ValI32
	ValI64                                     = impl.ValI64
	ValV128                                    = impl.ValV128
	Version                                    = impl.Version
)

func AsF32(b uint64) float32 { return impl.AsF32(b) }

func AsF64(b uint64) float64 { return impl.AsF64(b) }

func AsI32(b uint64) int32 { return impl.AsI32(b) }

func AsI64(b uint64) int64 { return impl.AsI64(b) }

func CapabilityDocs(docs string) CapabilityOption { return impl.CapabilityDocs(docs) }

func Capture(c *Compiled, opts SnapshotOptions) (*Snapshot, error) { return impl.Capture(c, opts) }

func Compile(args ...any) (*Compiled, error) { return impl.Compile(args...) }

func CompileWithConfig(cfg *RuntimeConfig, wasmBytes []byte) (*Compiled, error) {
	return impl.CompileWithConfig(cfg, wasmBytes)
}

func DirsFor(version string) Dirs { return impl.DirsFor(version) }

func F32(v float32) uint64 { return impl.F32(v) }

func F64(v float64) uint64 { return impl.F64(v) }

func GuardPageSupported() bool { return impl.GuardPageSupported() }

func GuestArgs() []string { return impl.GuestArgs() }

func I32(v int32) uint64 { return impl.I32(v) }

func I64(v int64) uint64 { return impl.I64(v) }

func Instantiate(source Instantiable, opts ...any) (*Instance, error) {
	return impl.Instantiate(source, opts...)
}

func IsCompiled(b []byte) bool { return impl.IsCompiled(b) }

func IsGuardPageUnavailable(err error) bool { return impl.IsGuardPageUnavailable(err) }

func IsSnapshot(b []byte) bool { return impl.IsSnapshot(b) }

func Load(b []byte) (*Compiled, error) { return impl.Load(b) }

func LoadSnapshot(b []byte) (*Snapshot, error) { return impl.LoadSnapshot(b) }

func MustCompile(wasmBytes []byte) *Compiled { return impl.MustCompile(wasmBytes) }

func NewExtension(name string) (Extension, bool) { return impl.NewExtension(name) }

func NewGlobalF32(v float32, mutable bool) *Global { return impl.NewGlobalF32(v, mutable) }

func NewGlobalF64(v float64, mutable bool) *Global { return impl.NewGlobalF64(v, mutable) }

func NewGlobalI32(v int32, mutable bool) *Global { return impl.NewGlobalI32(v, mutable) }

func NewGlobalI64(v int64, mutable bool) *Global { return impl.NewGlobalI64(v, mutable) }

func NewGlobalV128(v V128, mutable bool) *Global { return impl.NewGlobalV128(v, mutable) }

func NewHandleTable() *HandleTable { return impl.NewHandleTable() }

func NewMemory(minPages uint32, maxPages uint32) (*Memory, error) {
	return impl.NewMemory(minPages, maxPages)
}

func NewRuntime(opts ...RuntimeOption) *Runtime { return impl.NewRuntime(opts...) }

func NewRuntimeConfig() *RuntimeConfig { return impl.NewRuntimeConfig() }

func NewTable(minSize uint32, maxSize uint32) (*Table, error) { return impl.NewTable(minSize, maxSize) }

func NullExternRef() ExternRef { return impl.NullExternRef() }

func NullFuncRef() FuncRef { return impl.NullFuncRef() }

func Pool(snapshot *Snapshot, opts SnapshotPoolOptions) (*InstancePool, error) {
	return impl.Pool(snapshot, opts)
}

func ReadSnapshotFile(path string) (*Snapshot, error) { return impl.ReadSnapshotFile(path) }

func RegisterExtension(name string, factory ExtensionFactory) { impl.RegisterExtension(name, factory) }

func RegisteredPluginNames() []string { return impl.RegisteredPluginNames() }

func SetGuestArgs(args []string) { impl.SetGuestArgs(args) }

func SupportedFeatures() CoreFeatures { return impl.SupportedFeatures() }

func ValueExternRef(v ExternRef) Value { return impl.ValueExternRef(v) }

func ValueF32(v float32) Value { return impl.ValueF32(v) }

func ValueF64(v float64) Value { return impl.ValueF64(v) }

func ValueFuncRef(v FuncRef) Value { return impl.ValueFuncRef(v) }

func ValueI32(v int32) Value { return impl.ValueI32(v) }

func ValueI64(v int64) Value { return impl.ValueI64(v) }

func ValueOf(t ValType, bits uint64) Value { return impl.ValueOf(t, bits) }

func WithGC(gc GCConfig) InstantiateOption { return impl.WithGC(gc) }

func WithImportOverridePolicy(p ImportOverridePolicy) RuntimeOption {
	return impl.WithImportOverridePolicy(p)
}

func WithImports(im Imports) InstantiateOption { return impl.WithImports(im) }

func WithPolicy(p Policy) InstantiateOption { return impl.WithPolicy(p) }

func WithRuntimeConfig(cfg *RuntimeConfig) RuntimeOption { return impl.WithRuntimeConfig(cfg) }
