// Code generated by internal/genfacade; DO NOT EDIT.

// Package wago exposes compile, instantiate, and run helpers for WebAssembly
// modules. It is a generated facade over the implementation in src/wago, so
// callers import the stable path "github.com/wago-org/wago" while the code
// lives under src/wago alongside the rest of the engine.
package wago

//go:generate go run ./internal/genfacade

import impl "github.com/wago-org/wago/src/wago"

type (
	Compiled        = impl.Compiled
	DataInit        = impl.DataInit
	ElemInit        = impl.ElemInit
	FuncSig         = impl.FuncSig
	Global          = impl.Global
	GlobalDef       = impl.GlobalDef
	GlobalImport    = impl.GlobalImport
	GlobalImportDef = impl.GlobalImportDef
	HostFunc        = impl.HostFunc
	Imports         = impl.Imports
	Instance        = impl.Instance
	OffsetInit      = impl.OffsetInit
	Timings         = impl.Timings
	Value           = impl.Value
)

var (
	Compile                = impl.Compile
	CompileTimed           = impl.CompileTimed
	F32                    = impl.F32
	F64                    = impl.F64
	I32                    = impl.I32
	I64                    = impl.I64
	Instantiate            = impl.Instantiate
	InstantiateWithImports = impl.InstantiateWithImports
	IsCompiled             = impl.IsCompiled
	Load                   = impl.Load
	NewGlobal              = impl.NewGlobal
	Run                    = impl.Run
	RunValues              = impl.RunValues
	RunValuesWithHost      = impl.RunValuesWithHost
	RunValuesWithImports   = impl.RunValuesWithImports
	RunWithHost            = impl.RunWithHost
	RunWithImports         = impl.RunWithImports
)
