// Command geninstrnames packs InstrKind identifier suffixes into one string blob
// plus uint16 offsets. It keeps the release free of one string header/relocation
// per instruction while deriving names directly from the authoritative enum.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	in := flag.String("in", "types.go", "InstrKind source file")
	out := flag.String("out", "instr_names_gen.go", "generated Go output")
	flag.Parse()

	src, err := os.ReadFile(*in)
	if err != nil {
		fatal(err)
	}
	start := bytes.Index(src, []byte("InstrInvalid InstrKind = iota"))
	if start < 0 {
		fatal(fmt.Errorf("InstrKind enum start not found in %s", *in))
	}
	endRel := bytes.Index(src[start:], []byte("numInstrKinds"))
	if endRel < 0 {
		fatal(fmt.Errorf("InstrKind enum sentinel not found in %s", *in))
	}

	var names []string
	for _, line := range strings.Split(string(src[start:start+endRel]), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 || !strings.HasPrefix(fields[0], "Instr") {
			continue
		}
		name := strings.TrimPrefix(fields[0], "Instr")
		if name == "" {
			fatal(fmt.Errorf("empty instruction name in line %q", line))
		}
		names = append(names, name)
	}
	if len(names) == 0 {
		fatal(fmt.Errorf("no instruction names found in %s", *in))
	}

	var blob strings.Builder
	offsets := make([]int, 1, len(names)+1)
	for _, name := range names {
		blob.WriteString(name)
		if blob.Len() > int(^uint16(0)) {
			fatal(fmt.Errorf("instruction name blob is %d bytes; uint16 offsets overflow", blob.Len()))
		}
		offsets = append(offsets, blob.Len())
	}

	var generated strings.Builder
	generated.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	generated.WriteString("package wasm\n\n")
	fmt.Fprintf(&generated, "const instrKindNameCount = %d\n\n", len(names))
	generated.WriteString("const instrKindNameBlob = \"\" +\n")
	for i, name := range names {
		suffix := " +"
		if i == len(names)-1 {
			suffix = ""
		}
		fmt.Fprintf(&generated, "\t%s%s\n", strconv.Quote(name), suffix)
	}
	generated.WriteString("\nvar instrKindNameOffsets = [...]uint16{\n")
	for i, offset := range offsets {
		if i%12 == 0 {
			generated.WriteString("\t")
		}
		fmt.Fprintf(&generated, "%d,", offset)
		if i%12 == 11 || i == len(offsets)-1 {
			generated.WriteByte('\n')
		} else {
			generated.WriteByte(' ')
		}
	}
	generated.WriteString("}\n\n")
	generated.WriteString("var _ [numInstrKinds-instrKindNameCount]struct{}\n")
	generated.WriteString("var _ [instrKindNameCount-numInstrKinds]struct{}\n")

	formatted, err := format.Source([]byte(generated.String()))
	if err != nil {
		fatal(fmt.Errorf("format generated source: %w", err))
	}
	old, _ := os.ReadFile(*out)
	if bytes.Equal(old, formatted) {
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "geninstrnames:", err)
	os.Exit(1)
}
