// Command genmachinerules compiles the bounded machine-rule schema into plain
// Go matchers. Rule parsing and validation stay out of production binaries.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type rule struct {
	name, first, second, join, guard, output string
}

func main() {
	in := flag.String("in", "machine_rules.rules", "machine-rule source")
	out := flag.String("out", "machine_rules_gen.go", "generated Go output")
	pkg := flag.String("package", "", "generated package name")
	flag.Parse()
	if *pkg == "" {
		fatal(fmt.Errorf("-package is required"))
	}

	source, err := os.ReadFile(*in)
	if err != nil {
		fatal(err)
	}
	rules, err := parse(source)
	if err != nil {
		fatal(fmt.Errorf("%s: %w", *in, err))
	}
	generated, err := generate(*pkg, source, rules)
	if err != nil {
		fatal(err)
	}
	old, _ := os.ReadFile(*out)
	if bytes.Equal(old, generated) {
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*out, generated, 0o644); err != nil {
		fatal(err)
	}
}

func parse(source []byte) ([]rule, error) {
	var rules []rule
	s := bufio.NewScanner(bytes.NewReader(source))
	for line := 1; s.Scan(); line++ {
		text := strings.TrimSpace(s.Text())
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		fields := strings.Fields(text)
		if len(fields) != 6 {
			return nil, fmt.Errorf("line %d: want 6 fields, got %d", line, len(fields))
		}
		r := rule{name: fields[0], first: fields[1], second: fields[2], join: fields[3], guard: fields[4], output: fields[5]}
		if r.first != "swap" || r.second != "swap" || r.join != "first.src=second.dst" || r.guard != "first.dst!=second.src" || r.output != "swap-chain" {
			return nil, fmt.Errorf("line %d: unsupported rule shape %q", line, text)
		}
		for _, old := range rules {
			if old.name == r.name {
				return nil, fmt.Errorf("line %d: duplicate rule %q", line, r.name)
			}
		}
		rules = append(rules, r)
	}
	if err := s.Err(); err != nil {
		return nil, err
	}
	if len(rules) == 0 {
		return nil, fmt.Errorf("no rules")
	}
	return rules, nil
}

func generate(pkg string, source []byte, rules []rule) ([]byte, error) {
	var g strings.Builder
	if pkg == "amd64" || pkg == "arm64" {
		fmt.Fprintf(&g, "//go:build %s\n\n", pkg)
	}
	g.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&g, "package %s\n\n", pkg)
	fmt.Fprintf(&g, "const machineRuleSourceSHA256 = %q\n\n", fmt.Sprintf("%x", sha256.Sum256(source)))
	g.WriteString("type machineRuleID uint8\n\nconst (\n\tmachineRuleNone machineRuleID = iota\n")
	for _, r := range rules {
		fmt.Fprintf(&g, "\tmachineRule%s\n", exported(r.name))
	}
	g.WriteString(")\n\n")
	g.WriteString("type machineRuleMatch struct {\n\tid machineRuleID\n\ta, b, c Reg\n}\n\n")
	g.WriteString("func matchMachinePair(first, second machineOp) machineRuleMatch {\n")
	for _, r := range rules {
		fmt.Fprintf(&g, "\tif first.kind == machineSwap && second.kind == machineSwap && first.src == second.dst && first.dst != second.src {\n\t\treturn machineRuleMatch{id: machineRule%s, a: first.dst, b: first.src, c: second.src}\n\t}\n", exported(r.name))
	}
	g.WriteString("\treturn machineRuleMatch{}\n}\n\n")
	g.WriteString("func (id machineRuleID) String() string {\n\tswitch id {\n")
	for _, r := range rules {
		fmt.Fprintf(&g, "\tcase machineRule%s:\n\t\treturn %s\n", exported(r.name), strconv.Quote(r.name))
	}
	g.WriteString("\tdefault:\n\t\treturn \"none\"\n\t}\n}\n")

	formatted, err := format.Source([]byte(g.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func exported(name string) string {
	var out strings.Builder
	upper := true
	for _, r := range name {
		if r == '-' || r == '_' {
			upper = true
			continue
		}
		if upper && r >= 'a' && r <= 'z' {
			r -= 'a' - 'A'
		}
		out.WriteRune(r)
		upper = false
	}
	return out.String()
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genmachinerules:", err)
	os.Exit(1)
}
