package shared

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"go/format"
	"go/token"
	"strconv"

	"github.com/wago-org/wago/src/core/runtime/embedded32"
)

// Pico2FirmwareGoOptions controls the generated pure-Go descriptor for a
// bounded Arm32 or RV32 firmware image.
type Pico2FirmwareGoOptions struct {
	Package        string
	Symbol         string
	Target         uint32
	MaximumPayload uint32
}

// RenderPico2FirmwareGo emits a flash-friendly string snapshot and pure-Go
// embedded32 metadata for one closed firmware image.
func RenderPico2FirmwareGo(image *EmbeddedFirmwareImage, opts Pico2FirmwareGoOptions) ([]byte, error) {
	if image == nil {
		return nil, fmt.Errorf("embedded32: nil firmware image")
	}
	return renderPico2FirmwareGo(image.Bytes, image.BaseAddress, image, []uint32{image.ContextAddress}, opts)
}

// RenderPico2LinkedFirmwareGo emits one pure-Go descriptor for a root module in
// a linked image. Every module context is retained for transactional helper
// table patching during instantiation and reset.
func RenderPico2LinkedFirmwareGo(bundle *EmbeddedLinkedFirmwareImage, root int, opts Pico2FirmwareGoOptions) ([]byte, error) {
	if bundle == nil || root < 0 || root >= len(bundle.Modules) || bundle.Modules[root].Image == nil {
		return nil, fmt.Errorf("embedded32: invalid linked firmware root")
	}
	contexts := make([]uint32, len(bundle.Modules))
	for index := range bundle.Modules {
		if bundle.Modules[index].Image == nil {
			return nil, fmt.Errorf("embedded32: linked firmware module %d has no image", index)
		}
		contexts[index] = bundle.Modules[index].Image.ContextAddress
	}
	return renderPico2FirmwareGo(bundle.Bytes, bundle.BaseAddress, bundle.Modules[root].Image, contexts, opts)
}

func renderPico2FirmwareGo(imageBytes []byte, base uint32, root *EmbeddedFirmwareImage, contexts []uint32, opts Pico2FirmwareGoOptions) ([]byte, error) {
	if !pico2GoIdentifier(opts.Package) || !pico2GoIdentifier(opts.Symbol) {
		return nil, fmt.Errorf("embedded32: invalid Go image package or symbol")
	}
	if opts.Target != embedded32.TransportTargetArm32 && opts.Target != embedded32.TransportTargetRISCV32 {
		return nil, fmt.Errorf("embedded32: invalid Pico 2 target %d", opts.Target)
	}
	if opts.MaximumPayload == 0 || len(imageBytes) == 0 || uint64(len(imageBytes)) > uint64(^uint32(0)) ||
		base == 0 || root == nil || root.ContextAddress == 0 || len(contexts) == 0 {
		return nil, fmt.Errorf("embedded32: incomplete Pico 2 Go image metadata")
	}
	end := uint64(base) + uint64(len(imageBytes))
	if end > uint64(^uint32(0))+1 {
		return nil, fmt.Errorf("embedded32: Pico 2 Go image exceeds the 32-bit address space")
	}
	for index, context := range contexts {
		if uint64(context) < uint64(base) || uint64(context)+embedded32.ContextABISize > end {
			return nil, fmt.Errorf("embedded32: Pico 2 context %d is outside the image", index)
		}
		offset := context - base
		helper := binary.LittleEndian.Uint32(imageBytes[offset+embedded32.ContextHelperTableOffset:])
		if uint64(helper) < uint64(base) || uint64(helper)+embedded32.HelperTableBytes > end {
			return nil, fmt.Errorf("embedded32: Pico 2 helper table %d is outside the image", index)
		}
	}
	if root.StartAddress != 0 && !pico2GoCallable(root.StartAddress, base, end, opts.Target) {
		return nil, fmt.Errorf("embedded32: Pico 2 start entry is outside the image")
	}
	for index, function := range root.TransportFunctions {
		context := function.Context
		if context == 0 {
			context = root.ContextAddress
		}
		if !pico2GoCallable(function.Address, base, end, opts.Target) ||
			uint64(context) < uint64(base) || uint64(context)+embedded32.ContextABISize > end {
			return nil, fmt.Errorf("embedded32: Pico 2 transport function %d is outside the image", index)
		}
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by wago. DO NOT EDIT.")
	fmt.Fprintf(&out, "package %s\n\n", opts.Package)
	fmt.Fprintln(&out, "import \"github.com/wago-org/wago/src/core/runtime/embedded32\"")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "const %sInitialImage =\n", opts.Symbol)
	for offset := 0; offset < len(imageBytes); offset += 64 {
		end := offset + 64
		if end > len(imageBytes) {
			end = len(imageBytes)
		}
		fmt.Fprintf(&out, "\t%s", strconv.Quote(string(imageBytes[offset:end])))
		if end != len(imageBytes) {
			fmt.Fprint(&out, " +")
		}
		fmt.Fprintln(&out)
	}
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "var %sContexts = [...]uint32{\n", opts.Symbol)
	for _, context := range contexts {
		fmt.Fprintf(&out, "\t0x%08x,\n", context)
	}
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	if len(root.TransportFunctions) != 0 {
		fmt.Fprintf(&out, "var %sFunctions = [...]embedded32.FirmwareTransportFunction{\n", opts.Symbol)
		for _, function := range root.TransportFunctions {
			fmt.Fprintf(&out, "\t{Address: 0x%08x, Context: 0x%08x, ParamSlots: %d, ResultSlots: %d},\n",
				function.Address, function.Context, function.ParamSlots, function.ResultSlots)
		}
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
	}
	fmt.Fprintf(&out, "// %s is wired to caller-owned fixed SRAM and helper entries by board startup.\n", opts.Symbol)
	fmt.Fprintf(&out, "var %s = embedded32.FirmwareImageDescriptor{\n", opts.Symbol)
	fmt.Fprintf(&out, "\tTarget: %d,\n", opts.Target)
	fmt.Fprintf(&out, "\tMaximumPayload: %d,\n", opts.MaximumPayload)
	fmt.Fprintf(&out, "\tImageAddress: 0x%08x,\n", base)
	fmt.Fprintf(&out, "\tInitialImage: %sInitialImage,\n", opts.Symbol)
	fmt.Fprintf(&out, "\tContextAddress: 0x%08x,\n", root.ContextAddress)
	fmt.Fprintf(&out, "\tStartAddress: 0x%08x,\n", root.StartAddress)
	if len(root.TransportFunctions) != 0 {
		fmt.Fprintf(&out, "\tFunctions: %sFunctions[:],\n", opts.Symbol)
	}
	fmt.Fprintf(&out, "\tContexts: %sContexts[:],\n", opts.Symbol)
	fmt.Fprintln(&out, "}")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("embedded32: format generated Pico 2 Go image: %w", err)
	}
	return formatted, nil
}

// RenderPico2FirmwareMemoryScript emits a GNU ld fragment which reserves the
// image's fixed SRAM range without introducing any C source or initialized RAM
// payload. Board startup binds that range to FirmwareImageDescriptor.Image.
func RenderPico2FirmwareMemoryScript(symbol string, base, imageSize uint32) ([]byte, error) {
	if !pico2GoIdentifier(symbol) || base == 0 || imageSize == 0 || uint64(base)+uint64(imageSize) > uint64(^uint32(0))+1 {
		return nil, fmt.Errorf("embedded32: invalid Pico 2 memory reservation")
	}
	section := ".wago_pico2_image_" + symbol
	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by wago. DO NOT EDIT. */")
	fmt.Fprintln(&out, "SECTIONS")
	fmt.Fprintln(&out, "{")
	fmt.Fprintf(&out, "  %s 0x%08x (NOLOAD) : ALIGN(16)\n", section, base)
	fmt.Fprintln(&out, "  {")
	fmt.Fprintf(&out, "    . += %d;\n", imageSize)
	fmt.Fprintln(&out, "  } > RAM")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "INSERT AFTER .bss;")
	fmt.Fprintf(&out, "ASSERT(ADDR(%s) == 0x%08x, \"%s base address mismatch\");\n", section, base, symbol)
	fmt.Fprintf(&out, "ASSERT(SIZEOF(%s) == %d, \"%s image size mismatch\");\n", section, imageSize, symbol)
	return out.Bytes(), nil
}

func pico2GoCallable(callable, base uint32, end uint64, target uint32) bool {
	address := callable
	if target == embedded32.TransportTargetArm32 {
		if address&1 == 0 {
			return false
		}
		address &^= 1
	} else if address&1 != 0 {
		return false
	}
	return uint64(address) >= uint64(base) && uint64(address) < end
}

func pico2GoIdentifier(value string) bool {
	if value == "" || token.Lookup(value).IsKeyword() {
		return false
	}
	for index := range value {
		c := value[index]
		if c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || index > 0 && c >= '0' && c <= '9' {
			continue
		}
		return false
	}
	return true
}
