package shared

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"strings"

	"github.com/wago-org/wago/src/core/runtime/embedded32"
)

// Pico2FirmwareCOptions controls the freestanding C descriptor emitted for a
// bounded firmware image. Symbol must be a C identifier. Section defaults to a
// symbol-specific .wago_pico2_image section which the companion linker script
// places at the image's prelinked SRAM base address.
type Pico2FirmwareCOptions struct {
	Symbol         string
	Section        string
	Target         uint32
	MaximumPayload uint32
}

// RenderPico2FirmwareC emits flash snapshot bytes, fixed SRAM storage, callable
// export metadata, module contexts, and a wago_pico2_image descriptor for one
// closed firmware image.
func RenderPico2FirmwareC(image *EmbeddedFirmwareImage, opts Pico2FirmwareCOptions) ([]byte, error) {
	if image == nil {
		return nil, fmt.Errorf("embedded32: nil firmware image")
	}
	return renderPico2FirmwareC(image.Bytes, image.BaseAddress, image, []uint32{image.ContextAddress}, opts)
}

// RenderPico2LinkedFirmwareC emits one descriptor for a root module in a linked
// bundle. Every module context is included so instantiation patches all helper
// tables after restoring the bundle snapshot.
func RenderPico2LinkedFirmwareC(bundle *EmbeddedLinkedFirmwareImage, root int, opts Pico2FirmwareCOptions) ([]byte, error) {
	if bundle == nil || root < 0 || root >= len(bundle.Modules) || bundle.Modules[root].Image == nil {
		return nil, fmt.Errorf("embedded32: invalid linked firmware root")
	}
	contexts := make([]uint32, len(bundle.Modules))
	for i := range bundle.Modules {
		if bundle.Modules[i].Image == nil {
			return nil, fmt.Errorf("embedded32: linked firmware module %d has no image", i)
		}
		contexts[i] = bundle.Modules[i].Image.ContextAddress
	}
	return renderPico2FirmwareC(bundle.Bytes, bundle.BaseAddress, bundle.Modules[root].Image, contexts, opts)
}

func renderPico2FirmwareC(imageBytes []byte, base uint32, root *EmbeddedFirmwareImage, contexts []uint32, opts Pico2FirmwareCOptions) ([]byte, error) {
	if !pico2CIdentifier(opts.Symbol) {
		return nil, fmt.Errorf("embedded32: invalid C image symbol %q", opts.Symbol)
	}
	if opts.Target != embedded32.TransportTargetArm32 && opts.Target != embedded32.TransportTargetRISCV32 {
		return nil, fmt.Errorf("embedded32: invalid Pico 2 target %d", opts.Target)
	}
	if opts.MaximumPayload == 0 || len(imageBytes) == 0 || base == 0 || root == nil || root.ContextAddress == 0 || len(contexts) == 0 {
		return nil, fmt.Errorf("embedded32: incomplete Pico 2 C image metadata")
	}
	end := uint64(base) + uint64(len(imageBytes))
	if end > uint64(^uint32(0))+1 {
		return nil, fmt.Errorf("embedded32: Pico 2 C image exceeds the 32-bit address space")
	}
	for i, context := range contexts {
		if uint64(context) < uint64(base) || uint64(context)+embedded32.ContextABISize > end {
			return nil, fmt.Errorf("embedded32: Pico 2 context %d is outside the image", i)
		}
		offset := context - base
		helper := binary.LittleEndian.Uint32(imageBytes[offset+embedded32.ContextHelperTableOffset:])
		if uint64(helper) < uint64(base) || uint64(helper)+embedded32.HelperTableBytes > end {
			return nil, fmt.Errorf("embedded32: Pico 2 helper table %d is outside the image", i)
		}
	}
	if root.StartAddress != 0 && !pico2CallableInImage(root.StartAddress, base, end, opts.Target) {
		return nil, fmt.Errorf("embedded32: Pico 2 start entry is outside the image")
	}
	for i, function := range root.TransportFunctions {
		context := function.Context
		if context == 0 {
			context = root.ContextAddress
		}
		if !pico2CallableInImage(function.Address, base, end, opts.Target) ||
			uint64(context) < uint64(base) || uint64(context)+embedded32.ContextABISize > end {
			return nil, fmt.Errorf("embedded32: Pico 2 transport function %d is outside the image", i)
		}
	}
	section := opts.Section
	if section == "" {
		section = ".wago_pico2_image." + opts.Symbol
	}
	if !pico2CSection(section) {
		return nil, fmt.Errorf("embedded32: invalid C image section %q", section)
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by wago. DO NOT EDIT. */")
	fmt.Fprintln(&out, "#include \"wago_pico2.h\"")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "#if defined(__GNUC__) || defined(__clang__)")
	fmt.Fprintln(&out, "#define WAGO_PICO2_IMAGE_STORAGE(name) __attribute__((section(name), aligned(16), used))")
	fmt.Fprintln(&out, "#else")
	fmt.Fprintln(&out, "#define WAGO_PICO2_IMAGE_STORAGE(name)")
	fmt.Fprintln(&out, "#endif")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "static const uint8_t %s_initial_image[%d] = {\n", opts.Symbol, len(imageBytes))
	for i, value := range imageBytes {
		if i%12 == 0 {
			fmt.Fprint(&out, "    ")
		}
		fmt.Fprintf(&out, "0x%02x", value)
		if i+1 != len(imageBytes) {
			fmt.Fprint(&out, ", ")
		}
		if i%12 == 11 || i+1 == len(imageBytes) {
			fmt.Fprintln(&out)
		}
	}
	fmt.Fprintln(&out, "};")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "WAGO_PICO2_IMAGE_STORAGE(\"%s\")\n", section)
	fmt.Fprintf(&out, "uint8_t %s_image[%d];\n\n", opts.Symbol, len(imageBytes))

	functions := root.TransportFunctions
	if len(functions) != 0 {
		fmt.Fprintf(&out, "static const struct wago_pico2_function %s_functions[%d] = {\n", opts.Symbol, len(functions))
		for _, function := range functions {
			fmt.Fprintf(&out, "    {UINT32_C(0x%08x), UINT32_C(0x%08x), UINT16_C(%d), UINT16_C(%d)},\n",
				function.Address, function.Context, function.ParamSlots, function.ResultSlots)
		}
		fmt.Fprintln(&out, "};")
		fmt.Fprintln(&out)
	}
	fmt.Fprintf(&out, "static const uint32_t %s_contexts[%d] = {\n", opts.Symbol, len(contexts))
	for _, context := range contexts {
		fmt.Fprintf(&out, "    UINT32_C(0x%08x),\n", context)
	}
	fmt.Fprintln(&out, "};")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "const struct wago_pico2_image %s = {\n", opts.Symbol)
	fmt.Fprintf(&out, "    .target = UINT32_C(%d),\n", opts.Target)
	fmt.Fprintf(&out, "    .maximum_payload = UINT32_C(%d),\n", opts.MaximumPayload)
	fmt.Fprintf(&out, "    .load_address = UINT32_C(0x%08x),\n", base)
	fmt.Fprintf(&out, "    .image = %s_image,\n", opts.Symbol)
	fmt.Fprintf(&out, "    .initial_image = %s_initial_image,\n", opts.Symbol)
	fmt.Fprintf(&out, "    .image_size = UINT32_C(%d),\n", len(imageBytes))
	fmt.Fprintf(&out, "    .context_address = UINT32_C(0x%08x),\n", root.ContextAddress)
	fmt.Fprintf(&out, "    .start_address = UINT32_C(0x%08x),\n", root.StartAddress)
	if len(functions) == 0 {
		fmt.Fprintln(&out, "    .functions = NULL,")
	} else {
		fmt.Fprintf(&out, "    .functions = %s_functions,\n", opts.Symbol)
	}
	fmt.Fprintf(&out, "    .function_count = UINT32_C(%d),\n", len(functions))
	fmt.Fprintf(&out, "    .contexts = %s_contexts,\n", opts.Symbol)
	fmt.Fprintf(&out, "    .context_count = UINT32_C(%d),\n", len(contexts))
	fmt.Fprintln(&out, "};")
	return out.Bytes(), nil
}

// RenderPico2FirmwareLinkerScript emits the GNU ld fragment which reserves the
// generated mutable image section at its prelinked SRAM address without adding
// a second zero-filled flash payload.
func RenderPico2FirmwareLinkerScript(symbol, section string, base, imageSize uint32) ([]byte, error) {
	if !pico2CIdentifier(symbol) || base == 0 || imageSize == 0 {
		return nil, fmt.Errorf("embedded32: invalid Pico 2 linker metadata")
	}
	if section == "" {
		section = ".wago_pico2_image." + symbol
	}
	if !pico2CSection(section) {
		return nil, fmt.Errorf("embedded32: invalid C image section %q", section)
	}
	var out bytes.Buffer
	fmt.Fprintln(&out, "/* Code generated by wago. DO NOT EDIT. */")
	fmt.Fprintln(&out, "SECTIONS")
	fmt.Fprintln(&out, "{")
	fmt.Fprintf(&out, "  %s 0x%08x (NOLOAD) : ALIGN(16)\n", section, base)
	fmt.Fprintln(&out, "  {")
	fmt.Fprintf(&out, "    KEEP(*(%s))\n", section)
	fmt.Fprintln(&out, "  } > RAM")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out, "INSERT AFTER .bss;")
	fmt.Fprintf(&out, "ASSERT(ADDR(%s) == 0x%08x, \"%s base address mismatch\");\n", section, base, symbol)
	fmt.Fprintf(&out, "ASSERT(SIZEOF(%s) == %d, \"%s image size mismatch\");\n", section, imageSize, symbol)
	return out.Bytes(), nil
}

func pico2CallableInImage(callable, base uint32, end uint64, target uint32) bool {
	address := callable
	if target == embedded32.TransportTargetArm32 {
		if address&1 == 0 {
			return false
		}
		address &^= 1
	} else if address&1 != 0 {
		return false
	}
	return uint64(address) >= uint64(base) && uint64(address) < end
}

func pico2CIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for i := range value {
		c := value[i]
		if c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || i > 0 && c >= '0' && c <= '9' {
			continue
		}
		return false
	}
	return true
}

func pico2CSection(value string) bool {
	if value == "" || strings.Contains(value, "..") {
		return false
	}
	for i := range value {
		c := value[i]
		if c == '.' || c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' {
			continue
		}
		return false
	}
	return true
}
