package embedded32

import (
	"errors"
	"fmt"
)

const WasmPageSize = uint32(65536)

var (
	ErrArenaCapacity = errors.New("embedded32: arena capacity exceeded")
	ErrInvalidArena  = errors.New("embedded32: invalid arena configuration")
	ErrPublish       = errors.New("embedded32: code publication failed")
	ErrRuntimeBusy   = errors.New("embedded32: runtime invocation already active")
)

// LinearMemory is a fixed-capacity, explicitly-bounds-checked Wasm memory. The
// backing SRAM is supplied by firmware; Grow changes only the admitted prefix.
type LinearMemory struct {
	backing []byte
	pages   uint32
	max     uint32
}

func NewLinearMemory(backing []byte, initialPages, maximumPages uint32) (*LinearMemory, error) {
	if initialPages > maximumPages || uint64(maximumPages)*uint64(WasmPageSize) > uint64(len(backing)) {
		return nil, ErrInvalidArena
	}
	m := &LinearMemory{backing: backing, pages: initialPages, max: maximumPages}
	clear(m.backing[:maximumPages*WasmPageSize])
	return m, nil
}
func (m *LinearMemory) Pages() uint32        { return m.pages }
func (m *LinearMemory) MaximumPages() uint32 { return m.max }
func (m *LinearMemory) Bytes() []byte        { return m.backing[:m.pages*WasmPageSize] }
func (m *LinearMemory) Bounds(address, width uint32) bool {
	return uint64(address)+uint64(width) <= uint64(m.pages)*uint64(WasmPageSize)
}
func (m *LinearMemory) Range(address, width uint32) ([]byte, bool) {
	if !m.Bounds(address, width) {
		return nil, false
	}
	return m.backing[address : address+width], true
}
func (m *LinearMemory) Grow(delta uint32) (uint32, bool) {
	old := m.pages
	if delta > m.max-old {
		return old, false
	}
	next := old + delta
	clear(m.backing[old*WasmPageSize : next*WasmPageSize])
	m.pages = next
	return old, true
}
func (m *LinearMemory) Reset(initialPages uint32) bool {
	if initialPages > m.max {
		return false
	}
	clear(m.backing[:m.max*WasmPageSize])
	m.pages = initialPages
	return true
}

// CodePublisher performs the architecture-specific instruction publication
// step after generated bytes have been finalized in SRAM.
type CodePublisher func(offset uint32, code []byte) error

type CodeArena struct {
	backing         []byte
	used, published uint32
	active          bool
}
type CodeTransaction struct {
	start  uint32
	arena  *CodeArena
	closed bool
}
type CodeBlock struct {
	Offset uint32
	Bytes  []byte
}

func NewCodeArena(backing []byte) *CodeArena { clear(backing); return &CodeArena{backing: backing} }
func (a *CodeArena) Capacity() uint32        { return uint32(len(a.backing)) }
func (a *CodeArena) Used() uint32            { return a.used }
func (a *CodeArena) Published() uint32       { return a.published }
func (a *CodeArena) Begin() (CodeTransaction, error) {
	if a.active {
		return CodeTransaction{}, ErrInvalidArena
	}
	a.active = true
	return CodeTransaction{start: a.used, arena: a}, nil
}
func (t *CodeTransaction) Allocate(size, alignment uint32) (CodeBlock, error) {
	if t.closed || t.arena == nil || alignment == 0 || alignment&(alignment-1) != 0 {
		return CodeBlock{}, ErrInvalidArena
	}
	a := t.arena
	start := (a.used + alignment - 1) &^ (alignment - 1)
	end := uint64(start) + uint64(size)
	if end > uint64(len(a.backing)) {
		return CodeBlock{}, ErrArenaCapacity
	}
	clear(a.backing[start:uint32(end)])
	a.used = uint32(end)
	return CodeBlock{Offset: start, Bytes: a.backing[start:uint32(end)]}, nil
}
func (t *CodeTransaction) Commit(publish CodePublisher) error {
	if t.closed || t.arena == nil {
		return ErrInvalidArena
	}
	a := t.arena
	if t.start != a.published {
		t.rollback()
		return ErrInvalidArena
	}
	region := a.backing[t.start:a.used]
	if publish != nil {
		if err := publish(t.start, region); err != nil {
			t.rollback()
			return fmt.Errorf("%w: %v", ErrPublish, err)
		}
	}
	a.published = a.used
	a.active = false
	t.closed = true
	return nil
}
func (t *CodeTransaction) Rollback() {
	if !t.closed && t.arena != nil {
		t.rollback()
	}
}
func (t *CodeTransaction) rollback() {
	a := t.arena
	clear(a.backing[t.start:a.used])
	a.used = t.start
	a.active = false
	t.closed = true
}
func (a *CodeArena) Reset() { clear(a.backing); a.used = 0; a.published = 0; a.active = false }

// StackArena divides fixed SRAM into at most 32 equal native-stack slots.
type StackArena struct {
	backing []byte
	size    uint32
	slots   uint8
	used    uint32
}
type StackLease struct {
	Index uint8
	Bytes []byte
	arena *StackArena
}

func NewStackArena(backing []byte, stackSize uint32) (*StackArena, error) {
	if stackSize == 0 || stackSize&15 != 0 || len(backing)%int(stackSize) != 0 {
		return nil, ErrInvalidArena
	}
	slots := len(backing) / int(stackSize)
	if slots == 0 || slots > 32 {
		return nil, ErrInvalidArena
	}
	clear(backing)
	return &StackArena{backing: backing, size: stackSize, slots: uint8(slots)}, nil
}
func (a *StackArena) Acquire() (StackLease, error) {
	for i := uint8(0); i < a.slots; i++ {
		bit := uint32(1) << i
		if a.used&bit == 0 {
			a.used |= bit
			start := uint32(i) * a.size
			b := a.backing[start : start+a.size]
			clear(b)
			return StackLease{Index: i, Bytes: b, arena: a}, nil
		}
	}
	return StackLease{}, ErrArenaCapacity
}
func (l *StackLease) Release() bool {
	if l.arena == nil {
		return false
	}
	bit := uint32(1) << l.Index
	if l.arena.used&bit == 0 {
		return false
	}
	clear(l.Bytes)
	l.arena.used &^= bit
	l.arena = nil
	l.Bytes = nil
	return true
}
func (a *StackArena) InUse() int {
	n := 0
	for x := a.used; x != 0; x &= x - 1 {
		n++
	}
	return n
}

const (
	ExecutionRunning uint32 = iota
	ExecutionCanceled
)

type ControlCell struct {
	Trap   uint32
	Cancel uint32
}

func (c *ControlCell) Reset()         { c.Trap = 0; c.Cancel = 0 }
func (c *ControlCell) RequestCancel() { c.Cancel = 1 }
func (c *ControlCell) Poll() uint32 {
	if c.Cancel != 0 {
		return ExecutionCanceled
	}
	return ExecutionRunning
}

// ContextABI is the pointer-width-stable context passed to generated firmware
// code. Every field is a physical 32-bit target address or byte count.
type ContextABI struct {
	LinearMemoryBase    uint32
	LinearMemoryLength  uint32
	TrapCell            uint32
	CancelCell          uint32
	HelperTable         uint32
	LinearMemoryMaximum uint32
	StackLimit          uint32
	GlobalsBase         uint32
	DataSegmentsBase    uint32
	DataSegmentCount    uint32
	Table               uint32
	ImportsBase         uint32
	ImportedGlobalsBase uint32
}

const (
	ContextLinearMemoryBaseOffset    = 0
	ContextLinearMemoryLengthOffset  = 4
	ContextTrapCellOffset            = 8
	ContextCancelCellOffset          = 12
	ContextHelperTableOffset         = 16
	ContextLinearMemoryMaximumOffset = 20
	ContextStackLimitOffset          = 24
	ContextGlobalsBaseOffset         = 28
	ContextDataSegmentsBaseOffset    = 32
	ContextDataSegmentCountOffset    = 36
	ContextTableOffset               = 40
	ContextImportsBaseOffset         = 44
	ContextImportedGlobalsBaseOffset = 48
	ContextABISize                   = 52
)

// Runtime composes the fixed embedded resources. The initial profile permits
// one active invocation, matching the no-threads product boundary.
type Runtime struct {
	Memory  *LinearMemory
	Code    *CodeArena
	Stacks  *StackArena
	Control ControlCell
	active  bool
}
type Invocation struct {
	Stack   StackLease
	runtime *Runtime
}

func NewRuntime(memory *LinearMemory, code *CodeArena, stacks *StackArena) (*Runtime, error) {
	if memory == nil || code == nil || stacks == nil {
		return nil, ErrInvalidArena
	}
	return &Runtime{Memory: memory, Code: code, Stacks: stacks}, nil
}
func (r *Runtime) BeginInvocation() (Invocation, error) {
	if r.active {
		return Invocation{}, ErrRuntimeBusy
	}
	stack, err := r.Stacks.Acquire()
	if err != nil {
		return Invocation{}, err
	}
	r.Control.Reset()
	r.active = true
	return Invocation{Stack: stack, runtime: r}, nil
}
func (i *Invocation) Control() *ControlCell {
	if i.runtime == nil {
		return nil
	}
	return &i.runtime.Control
}
func (i *Invocation) End() bool {
	if i.runtime == nil {
		return false
	}
	r := i.runtime
	if !i.Stack.Release() {
		return false
	}
	r.active = false
	i.runtime = nil
	return true
}
func (r *Runtime) Reset(initialPages uint32) bool {
	if r.active {
		return false
	}
	if !r.Memory.Reset(initialPages) {
		return false
	}
	r.Code.Reset()
	r.Control.Reset()
	return true
}
