//go:build amd64 && wago_profile

package amd64

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"testing"

	"github.com/wago-org/wago/internal/jitprofile"
	"github.com/wago-org/wago/src/core/compiler/wasm"
	"github.com/wago-org/wago/tests/support/wasmtest"
)

func TestProfileUnwindFinalizedFixedFrames(t *testing.T) {
	var types, bodies, exports [][]byte
	for i := 0; i < 24; i++ {
		typeIndex := uint32(0)
		if i%6 >= 4 {
			typeIndex = 1
		}
		types = append(types, wasmtest.ULEB(typeIndex))
		body := []byte{0x20, 0, 0xb}
		if i%6 == 1 {
			body = []byte{0x20, 0, 0x28, 2, 0, 0xb}
		}
		if i%6 == 2 {
			body = append([]byte{0x20, 0, 0x10}, wasmtest.ULEB(uint32(i+1))...)
			body = append(body, 0xb)
		}
		if i%6 == 3 {
			body = []byte{0x20, 0, 0x10, 0, 0xb}
		}
		if i%6 == 4 {
			body = append([]byte{0x20, 0, 0x20, 1, 0x10}, wasmtest.ULEB(uint32(i+1))...)
			body = append(body, 0xb)
		}
		if i%6 == 5 {
			body = []byte{0x20, 1, 0xb}
		}
		bodies = append(bodies, wasmtest.Code(body))
		exports = append(exports, wasmtest.ExportEntry(fmt.Sprintf("f%d", i), 0, uint32(i+1)))
	}
	data := wasmtest.Module(
		wasmtest.Section(1, wasmtest.Vec(wasmtest.FuncType([]wasm.ValType{wasm.I32}, []wasm.ValType{wasm.I32}), wasmtest.FuncType([]wasm.ValType{wasm.I32, wasm.F64}, []wasm.ValType{wasm.F64}))),
		wasmtest.Section(2, wasmtest.Vec([]byte{1, 'm', 1, 'f', 0, 0})),
		wasmtest.Section(3, wasmtest.Vec(types...)),
		wasmtest.Section(5, wasmtest.Vec([]byte{0, 1})),
		wasmtest.Section(7, wasmtest.Vec(exports...)),
		wasmtest.Section(10, wasmtest.Vec(bodies...)),
	)
	for _, regABI := range []bool{false, true} {
		for _, compact := range []bool{false, true} {
			for _, workers := range []int{1, 4} {
				for _, exportAll := range []bool{false, true} {
					t.Run(fmt.Sprintf("reg=%v/compact=%v/workers=%d/exports=%v", regABI, compact, workers, exportAll), func(t *testing.T) {
						m, err := wasm.DecodeModule(data)
						if err != nil {
							t.Fatal(err)
						}
						if !exportAll {
							m.Exports = m.Exports[:1]
						}
						opts := CompileOptions{DeferCodeMapping: true, CompactNative: compact, Workers: workers, Optimizations: map[string]bool{"reg-abi": regABI, "inline": false}}
						plain, err := CompileModuleWith(m, opts)
						if err != nil {
							t.Fatal(err)
						}
						var stats ModuleStats
						opts.Profile, opts.UnwindMaps, opts.Stats = true, true, &stats
						observed, err := CompileModuleWith(m, opts)
						if err != nil {
							t.Fatal(err)
						}
						if !bytes.Equal(plain.Code, observed.Code) {
							t.Fatal("unwind metadata changed generated bytes")
						}
						if err := jitprofile.ValidateUnwind(stats.UnwindRanges, uint64(len(observed.Code))); err != nil {
							t.Fatal(err)
						}
						for i, f := range stats.Funcs {
							start := observed.Entry[i] + f.NativeSize.HostAdapterBytes + f.NativeSize.AdapterToInternalPaddingBytes
							if i%6 == 3 {
								if len(f.UnwindRanges) != 0 {
									t.Fatal("host caller admitted as fixed-frame body")
								}
								if _, ok := jitprofile.LookupUnwind(stats.UnwindRanges, uint64(start)); ok {
									t.Fatal("unknown caller mapped")
								}
								continue
							}
							if len(f.UnwindRanges) == 0 {
								t.Fatalf("function %d missing rules", i)
							}
							last := f.UnwindRanges[len(f.UnwindRanges)-1]
							end := start + int(last.Offset+last.Size) - f.UnwindInternalOffset
							if observed.Code[end-1] != 0xc3 {
								t.Fatal("unwind body does not end at RET")
							}
							subSize, addSize := 0, 0
							if !(compact && f.FrameBytes == 0) {
								subSize = unwindFrameInstruction(t, observed.Code[start:], 0xec, f.FrameBytes)
								addSize = subSize
								if unwindFrameInstruction(t, observed.Code[end-1-addSize:], 0xc4, f.FrameBytes) != addSize {
									t.Fatal("different frame adjustments")
								}
							}
							for pc := start; pc < end; pc++ {
								r, ok := jitprofile.LookupUnwind(stats.UnwindRanges, uint64(pc))
								want := int64(f.FrameBytes) + 8
								if pc < start+subSize || pc == end-1 {
									want = 8
								}
								if !ok || r.CFARegister != 7 || r.CFAOffset != want || r.ReturnOffset != -8 {
									t.Fatalf("function %d PC=%d: %+v, present=%v, want CFA %d", i, pc, r, ok, want)
								}
							}
							if r, ok := jitprofile.LookupUnwind(stats.UnwindRanges, uint64(end)); ok && r.Offset < uint64(end) {
								t.Fatal("rule extended past RET")
							}
							adapterEnd := observed.Entry[i] + f.NativeSize.HostAdapterBytes
							for pc := observed.Entry[i]; pc < adapterEnd; pc++ {
								if _, ok := jitprofile.LookupUnwind(stats.UnwindRanges, uint64(pc)); !ok {
									t.Fatal("adapter lost recovery rules", i, pc)
								}
							}
							for pc := adapterEnd; pc < start; pc++ {
								if _, ok := jitprofile.LookupUnwind(stats.UnwindRanges, uint64(pc)); ok {
									t.Fatal("adapter alignment padding mapped", i, pc)
								}
							}
						}
					})
				}
			}
		}
	}
}

func unwindFrameInstruction(t *testing.T, code []byte, opcode byte, frame int) int {
	t.Helper()
	if len(code) >= 7 && code[0] == 0x48 && code[1] == 0x81 && code[2] == opcode && binary.LittleEndian.Uint32(code[3:]) == uint32(frame) {
		return 7
	}
	if len(code) >= 4 && code[0] == 0x48 && code[1] == 0x83 && code[2] == opcode && int(code[3]) == frame {
		return 4
	}
	t.Fatalf("unexpected frame instruction %x, frame %d", code, frame)
	return 0
}
