//go:build arm64

package arm64

import (
	"testing"

	"github.com/wago-org/wago/src/core/compiler/wasm"
)

func TestDirectOnlyFunctionOmitsHostAdapter(t *testing.T) {
	i32 := []wasm.ValType{wasm.I32}
	m := modFuncs(t,
		funcDef{i32, i32, []byte{0x00, 0x20, 0x00, 0x10, 0x01, 0x0b}},
		funcDef{i32, i32, []byte{0x00, 0x20, 0x00, 0x41, 0x01, 0x6a, 0x0b}},
	)
	cm, err := CompileModule(m)
	if err != nil {
		t.Fatal(err)
	}
	if cm.Entry[0] == cm.InternalEntry[0] {
		t.Fatal("exported function lost its host adapter")
	}
	if cm.Entry[1] != cm.InternalEntry[1] {
		t.Fatalf("direct-only entry/internal = %d/%d, want one internal entry", cm.Entry[1], cm.InternalEntry[1])
	}

	m.Exports = append(m.Exports, wasm.Export{Name: "callee", Index: wasm.ExternIdx{Kind: wasm.ExternFunc, Index: 1}})
	withAdapter, err := CompileModule(m)
	if err != nil {
		t.Fatal(err)
	}
	if withAdapter.Entry[1] == withAdapter.InternalEntry[1] {
		t.Fatal("newly exported callee did not retain a host adapter")
	}
	if len(withAdapter.Code) <= len(cm.Code) {
		t.Fatalf("adapter-equipped code = %d bytes, direct-only = %d", len(withAdapter.Code), len(cm.Code))
	}
	t.Logf("one direct-only adapter removed %d generated bytes", len(withAdapter.Code)-len(cm.Code))
}
