//go:build arm64

// Code generated by go generate; DO NOT EDIT.

package arm64

const machineRuleSourceSHA256 = "fb764a68dc4eab11a130046fab974cb704a51f5b0f01ea496b078b85f9a01d4f"

type machineRuleID uint8

const (
	machineRuleNone machineRuleID = iota
	machineRuleSwapChain3
)

type machineRuleMatch struct {
	id      machineRuleID
	a, b, c Reg
}

func matchMachinePair(first, second machineOp) machineRuleMatch {
	if first.kind == machineSwap && second.kind == machineSwap && first.src == second.dst && first.dst != second.src {
		return machineRuleMatch{id: machineRuleSwapChain3, a: first.dst, b: first.src, c: second.src}
	}
	return machineRuleMatch{}
}

func (id machineRuleID) String() string {
	switch id {
	case machineRuleSwapChain3:
		return "swap-chain-3"
	default:
		return "none"
	}
}
