#!/usr/bin/env sh
# Run and count the five public verification gates. The headline is a count of
# checks, not unique source assertions: each independently required gate earns
# its own accounting row.
set -eu

report="${VERIFY_REPORT:-VERIFICATION.md}"
root=$(git rev-parse --show-toplevel) || {
	printf 'wago: not inside a git repository\n' >&2
	exit 1
}
cd "$root"

command -v wast2json >/dev/null 2>&1 || {
	printf 'wast2json (wabt) not on PATH\n' >&2
	exit 1
}
[ -f tests/spec/i32.wast ] || git submodule update --init tests/spec
[ -f tests/spec-v2/test/core/i32.wast ] || git submodule update --init tests/spec-v2

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT HUP INT TERM

count_tests() {
	awk -F'"' '
		{
			action=""; hastest=0
			for (i=1; i<NF; i++) {
				if ($i=="Action") action=$(i+2)
				if ($i=="Test") hastest=1
			}
			if (hastest) {
				if (action=="pass") p++
				else if (action=="fail") f++
				else if (action=="skip") s++
			}
		}
		END { printf "%d\t%d\t%d\n", p+0, f+0, s+0 }
	' "$@"
}

spec_total() {
	version=$1
	shift
	line=$(grep "TOTAL\[$version\]:" "$@" | tail -1)
	[ -n "$line" ] || {
		printf 'verification: no TOTAL[%s] accounting line\n' "$version" >&2
		exit 1
	}
	printf '%s\n' "$line" | sed -nE \
		's/.*assertions passed=([0-9]+) failed=([0-9]+) skipped=([0-9]+).*/\1	\2	\3/p'
}

go test -count=1 -json ./... >"$tmp/normal.json"
normal=$(count_tests "$tmp/normal.json")

go test -count=1 -json -tags wago_guardpage ./src/wago/ >"$tmp/guard-root.json"
(cd bench && go test -count=1 -json -tags wago_guardpage \
	-run 'TestCorpusDifferential|TestJsonAsGuardCorrect' .) >"$tmp/guard-bench.json"
guard=$(count_tests "$tmp/guard-root.json" "$tmp/guard-bench.json")

WAGO_SPECTEST_DIR="$root/tests/spec" WAGO_SPEC_VERSION=1.0 \
	go test -count=1 -run TestSpecSuiteExec -v ./src/wago/ >"$tmp/spec1.log"
spec1=$(spec_total 1.0 "$tmp/spec1.log")

go test -count=1 -run '^TestWazeroPortPinnedCoreV2Validation$' -v \
	./src/core/compiler/wasm/ >"$tmp/spec2-validation.log"
WAGO_SPECTEST_DIR="$root/tests/spec-v2" WAGO_SPEC_VERSION=2.0 \
	go test -count=1 -run '^TestWazeroPortPinnedCoreV2SpecExecution$' -v \
	./src/wago/ >"$tmp/spec2-execution.log"
spec2_validation=$(spec_total 2.0 "$tmp/spec2-validation.log")
spec2_execution=$(spec_total 2.0 "$tmp/spec2-execution.log")

WAGO_SPECTEST_DIR="$root/tests/spec" WAGO_SPEC_VERSION=simd \
	go test -count=1 -run TestSpecSuiteExec -v ./src/wago/ >"$tmp/simd.log"
simd=$(spec_total simd "$tmp/simd.log")

field() {
	printf '%s' "$1" | cut -f"$2"
}

normal_pass=$(field "$normal" 1)
normal_fail=$(field "$normal" 2)
normal_skip=$(field "$normal" 3)
guard_pass=$(field "$guard" 1)
guard_fail=$(field "$guard" 2)
guard_skip=$(field "$guard" 3)
spec1_pass=$(field "$spec1" 1)
spec1_fail=$(field "$spec1" 2)
spec2_validation_pass=$(field "$spec2_validation" 1)
spec2_validation_fail=$(field "$spec2_validation" 2)
spec2_execution_pass=$(field "$spec2_execution" 1)
spec2_execution_fail=$(field "$spec2_execution" 2)
simd_pass=$(field "$simd" 1)
simd_fail=$(field "$simd" 2)

spec2_pass=$((spec2_validation_pass + spec2_execution_pass))
spec2_fail=$((spec2_validation_fail + spec2_execution_fail))
passed=$((normal_pass + guard_pass + spec1_pass + spec2_pass + simd_pass))
failed=$((normal_fail + guard_fail + spec1_fail + spec2_fail + simd_fail))
skipped=$((normal_skip + guard_skip))

cover_report="${COVER_REPORT:-coverage-report.md}"
COVERPROFILE="${COVERPROFILE:-coverage.out}" COVER_REPORT="$cover_report" scripts/coverage.sh
coverage=$(sed -nE 's/^Coverage: ([0-9.]+)%.*/\1/p' "$cover_report" | head -1)
[ -n "$coverage" ] || {
	printf 'verification: no coverage summary in %s\n' "$cover_report" >&2
	exit 1
}

{
	printf '# Public verification\n\n'
	printf 'Generated by `make verify-public` on `%s/%s`.\n\n' "$(go env GOOS)" "$(go env GOARCH)"
	printf '**Verification: checks pass=%d fail=%d skip=%d**\n\n' "$passed" "$failed" "$skipped"
	printf '**Coverage: %s%%**\n\n' "$coverage"
	printf '| Gate | Passed checks | Failed | Skipped | Accounting unit |\n'
	printf '|---|---:|---:|---:|---|\n'
	printf '| Normal | %d | %d | %d | Go tests and subtests |\n' "$normal_pass" "$normal_fail" "$normal_skip"
	printf '| Guard pages | %d | %d | %d | Go tests and subtests |\n' "$guard_pass" "$guard_fail" "$guard_skip"
	printf '| Spec 1.0 | %d | %d | 0 | execution assertions |\n' "$spec1_pass" "$spec1_fail"
	printf '| Spec 2.0 | %d | %d | 0 | %d validation + %d execution assertions |\n' \
		"$spec2_pass" "$spec2_fail" "$spec2_validation_pass" "$spec2_execution_pass"
	printf '| SIMD | %d | %d | 0 | execution assertions |\n' "$simd_pass" "$simd_fail"
} >"$report"

printf 'Verification: %d checks passed, %d failed, %d skipped\n' "$passed" "$failed" "$skipped"
