// Package semanticcorpus loads and executes Wago's semantic corpus: real
// programs compiled to wasm, each pinned to an upstream revision and checked
// against an exact, independently verifiable oracle (published vectors, native
// differentials, or upstream self-check values). A module that merely runs to
// completion does not count as a pass; the expected result must match exactly.
package semanticcorpus

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
)

// Manifest is the top-level corpus inventory (tests/corpora/MANIFEST.json).
type Manifest struct {
	Schema  int      `json:"schema"`
	Modules []Module `json:"modules"`
}

// Module is one corpus case: a checked-in wasm artifact plus the exact inputs
// and oracle that make execution a semantic check rather than a smoke test.
type Module struct {
	ID             string   `json:"id"`
	Artifact       string   `json:"artifact"`
	ArtifactSHA256 string   `json:"artifact_sha256"`
	ABI            string   `json:"abi"`
	Source         Source   `json:"source"`
	Invoke         Invoke   `json:"invoke"`
	Expect         Expect   `json:"expect"`
	Limits         Limits   `json:"limits"`
	Tags           []string `json:"tags"`
	// KnownIssue, when non-empty, records a runtime discrepancy that blocks
	// this case from passing today (e.g. a wago JIT bug). The case is skipped
	// by the execution gate with this message and re-enabled by clearing the
	// field once the issue is fixed — the pinned artifact, oracle, and build
	// script stay checked in so the case is never silently dropped.
	KnownIssue string `json:"known_issue,omitempty"`
}

// Source records provenance for the corpus case.
type Source struct {
	Repository       string `json:"repository"`
	Revision         string `json:"revision"`
	RevisionDate     string `json:"revision_date"`
	License          string `json:"license"`
	Toolchain        string `json:"toolchain"`
	ToolchainVersion string `json:"toolchain_version"`
}

// Invoke describes how to drive the module through the core ABI. Exactly one
// of the single-invocation shape (Args + Expect) or the published-vectors shape
// (Vectors) must be present.
//
// In single-invocation mode, when Input is set it is written to the buffer
// returned by InputPtrExport, and Expect.Memory offsets are relative to the
// buffer returned by OutputPtrExport. Runners therefore own their buffer
// addresses rather than the corpus assuming a linear-memory layout.
type Invoke struct {
	Export          string   `json:"export"`
	Args            []int32  `json:"args,omitempty"`
	Input           string   `json:"input,omitempty"`
	InputPtrExport  string   `json:"input_ptr_export,omitempty"`
	OutputPtrExport string   `json:"output_ptr_export,omitempty"`
	Vectors         *Vectors `json:"vectors,omitempty"`
}

// Vectors is a published-vector oracle (document strength 1). For each case it
// writes a generated input pattern of case.Len bytes at InputOffset, invokes
// Export(InputOffset, case.Len, OutputOffset), and compares the OutputLen bytes
// read from OutputOffset against the published case.Out digest.
type Vectors struct {
	InputOffset  uint32 `json:"input_offset"`
	OutputOffset uint32 `json:"output_offset"`
	// InputPtrExport / OutputPtrExport, when set, name zero-arg exports that
	// return the guest's input/output buffer addresses. They take precedence
	// over InputOffset / OutputOffset so the corpus never assumes the guest's
	// stack/static-data layout.
	InputPtrExport  string       `json:"input_ptr_export,omitempty"`
	OutputPtrExport string       `json:"output_ptr_export,omitempty"`
	OutputLen       int          `json:"output_len"`
	Mod             int          `json:"mod,omitempty"` // generated byte i = i % Mod (0 disables)
	Cases           []VectorCase `json:"cases"`
}

// VectorCase is one published input length and its exact expected output.
type VectorCase struct {
	Len int    `json:"len"`
	Out string `json:"out"`
}

// MemoryCell is bytes written into (inputs) or compared from (outputs) linear
// memory at a fixed offset.
type MemoryCell struct {
	Offset uint32 `json:"offset"`
	Hex    string `json:"hex"`
}

// Expect is the exact oracle for one invocation.
type Expect struct {
	Return []string     `json:"return,omitempty"`
	Memory []MemoryCell `json:"memory,omitempty"`
}

// Limits bounds execution so a miscompiled guest cannot hang the suite.
type Limits struct {
	TimeoutMS int `json:"timeout_ms"`
}

// LoadManifest reads and strictly validates the corpus manifest at path.
func LoadManifest(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var m Manifest
	if err := dec.Decode(&m); err != nil {
		return nil, fmt.Errorf("decode manifest: %w", err)
	}
	var trailing any
	if err := dec.Decode(&trailing); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("decode manifest: trailing JSON value")
		}
		return nil, fmt.Errorf("decode manifest trailing content: %w", err)
	}
	if m.Schema != 1 {
		return nil, fmt.Errorf("manifest schema = %d, want 1", m.Schema)
	}
	if len(m.Modules) == 0 {
		return nil, fmt.Errorf("manifest declares no modules")
	}
	if err := validate(&m); err != nil {
		return nil, err
	}
	return &m, nil
}

func validate(m *Manifest) error {
	seen := make(map[string]bool, len(m.Modules))
	for i := range m.Modules {
		mod := &m.Modules[i]
		if mod.ID == "" {
			return fmt.Errorf("module %d: empty id", i)
		}
		if seen[mod.ID] {
			return fmt.Errorf("duplicate module id %q", mod.ID)
		}
		seen[mod.ID] = true
		if mod.Artifact == "" || mod.ArtifactSHA256 == "" {
			return fmt.Errorf("module %q: artifact and artifact_sha256 are required", mod.ID)
		}
		if len(mod.ArtifactSHA256) != 64 {
			return fmt.Errorf("module %q: artifact_sha256 must be 64 hex chars", mod.ID)
		}
		if _, err := hex.DecodeString(mod.ArtifactSHA256); err != nil {
			return fmt.Errorf("module %q: artifact_sha256: %w", mod.ID, err)
		}
		if mod.ABI != "core" {
			return fmt.Errorf("module %q: abi = %q, want %q (wasi-preview1 is a later tranche)", mod.ID, mod.ABI, "core")
		}
		if err := validateSource(mod.ID, mod.Source); err != nil {
			return err
		}
		if mod.Invoke.Export == "" {
			return fmt.Errorf("module %q: invoke.export is required", mod.ID)
		}
		if mod.Limits.TimeoutMS <= 0 {
			return fmt.Errorf("module %q: limits.timeout_ms must be positive", mod.ID)
		}
		hasVectors := mod.Invoke.Vectors != nil
		hasExpect := len(mod.Expect.Return) > 0 || len(mod.Expect.Memory) > 0
		if hasVectors == hasExpect {
			return fmt.Errorf("module %q: declare exactly one oracle shape (invoke.vectors, or args+expect)", mod.ID)
		}
		if _, err := hex.DecodeString(mod.Invoke.Input); err != nil {
			return fmt.Errorf("module %q: invoke.input: %w", mod.ID, err)
		}
		if mod.Invoke.Input != "" && mod.Invoke.InputPtrExport == "" {
			return fmt.Errorf("module %q: invoke.input requires invoke.input_ptr_export", mod.ID)
		}
		if hasVectors {
			if err := validateVectors(mod.ID, mod.Invoke.Vectors); err != nil {
				return err
			}
			continue
		}
		for j, cell := range mod.Expect.Memory {
			if _, err := hex.DecodeString(cell.Hex); err != nil {
				return fmt.Errorf("module %q memory oracle %d: hex: %w", mod.ID, j, err)
			}
		}
		for j, r := range mod.Expect.Return {
			if _, err := parseHexUint64(r); err != nil {
				return fmt.Errorf("module %q return oracle %d: %w", mod.ID, j, err)
			}
		}
	}
	return nil
}

func validateVectors(id string, v *Vectors) error {
	if v.OutputLen <= 0 {
		return fmt.Errorf("module %q: vectors.output_len must be positive", id)
	}
	if v.Mod < 0 {
		return fmt.Errorf("module %q: vectors.mod must be >= 0", id)
	}
	if len(v.Cases) == 0 {
		return fmt.Errorf("module %q: vectors.cases must not be empty", id)
	}
	for j, c := range v.Cases {
		if c.Len < 0 {
			return fmt.Errorf("module %q: vectors.cases[%d].len must be >= 0", id, j)
		}
		out, err := hex.DecodeString(c.Out)
		if err != nil {
			return fmt.Errorf("module %q: vectors.cases[%d].out: %w", id, j, err)
		}
		if len(out) != v.OutputLen {
			return fmt.Errorf("module %q: vectors.cases[%d].out length = %d bytes, want output_len %d", id, j, len(out), v.OutputLen)
		}
	}
	return nil
}

func validateSource(id string, s Source) error {
	if s.Repository == "" || s.Revision == "" || s.RevisionDate == "" || s.License == "" {
		return fmt.Errorf("module %q: source provenance (repository, revision, revision_date, license) is required", id)
	}
	if s.Toolchain == "" || s.ToolchainVersion == "" {
		return fmt.Errorf("module %q: source toolchain and toolchain_version are required", id)
	}
	return nil
}

// CorpusRoot returns the checked-in corpus directory (tests/corpora) relative
// to this package's directory.
func CorpusRoot() string {
	return filepath.Clean(filepath.Join("..", "corpora"))
}

// ManifestPath returns the manifest path relative to this package's directory.
func ManifestPath() string {
	return filepath.Join(CorpusRoot(), "MANIFEST.json")
}

// sortedModuleIDs returns the manifest module ids in deterministic order.
//
//lint:ignore U1000 retained for deterministic corpus tooling and reports
func sortedModuleIDs(m *Manifest) []string {
	ids := make([]string, len(m.Modules))
	for i, mod := range m.Modules {
		ids[i] = mod.ID
	}
	sort.Strings(ids)
	return ids
}
