// Code generated by railspecgen; DO NOT EDIT.

package railspec

type TargetMask uint8

const (
	TargetAMD64 TargetMask = 1 << iota
	TargetARM64
)

type RuleID uint8

const (
	RuleInvalid RuleID = iota
	RuleGenericRegister
	RuleAMD64Imm32
	RuleAMD64ShiftCL
	RuleAMD64DivFixed
	RuleARM64Imm12
	RuleFoldedMemoryAddress
	RuleCompareBranchFlags
)

type OperandForm uint8

const (
	FormInvalid OperandForm = iota
	FormRegister
	FormSignedImm32
	FormFixedGPR1
	FormFixedGPR0
	FormUnsignedImm12
	FormAddress
	FormFlags
)

type Rule struct {
	ID          RuleID
	Targets     TargetMask
	NativeBytes uint8
	Latency     uint8
	Uops        uint8
	Forms       [3]OperandForm
	FormCount   uint8
	Verified    bool
}

var Rules = [...]Rule{
	{},
	{ID: RuleGenericRegister, Targets: TargetAMD64 | TargetARM64, NativeBytes: 4, Latency: 1, Uops: 1, Forms: [3]OperandForm{FormRegister}, FormCount: 1, Verified: true},
	{ID: RuleAMD64Imm32, Targets: TargetAMD64, NativeBytes: 6, Latency: 1, Uops: 1, Forms: [3]OperandForm{FormRegister, FormSignedImm32}, FormCount: 2, Verified: true},
	{ID: RuleAMD64ShiftCL, Targets: TargetAMD64, NativeBytes: 3, Latency: 1, Uops: 1, Forms: [3]OperandForm{FormRegister, FormFixedGPR1}, FormCount: 2, Verified: true},
	{ID: RuleAMD64DivFixed, Targets: TargetAMD64, NativeBytes: 4, Latency: 16, Uops: 4, Forms: [3]OperandForm{FormFixedGPR0, FormRegister}, FormCount: 2, Verified: true},
	{ID: RuleARM64Imm12, Targets: TargetARM64, NativeBytes: 4, Latency: 1, Uops: 1, Forms: [3]OperandForm{FormRegister, FormUnsignedImm12}, FormCount: 2, Verified: true},
	{ID: RuleFoldedMemoryAddress, Targets: TargetAMD64 | TargetARM64, NativeBytes: 4, Latency: 4, Uops: 1, Forms: [3]OperandForm{FormAddress, FormRegister}, FormCount: 2, Verified: true},
	{ID: RuleCompareBranchFlags, Targets: TargetAMD64 | TargetARM64, NativeBytes: 6, Latency: 1, Uops: 1, Forms: [3]OperandForm{FormRegister, FormRegister, FormFlags}, FormCount: 3, Verified: true},
}
